MYSQL_NOT_AVAILABLE = 0;
MYSQL_CONN_ERROR = 1;
MYSQL_SETUP_MISSING = 2;

MANGOS_CHARDB_NOT_FOUND = 3;
MANGOS_MANGOSDB_NOT_FOUND = 4;
MANGOS_REALMDDB_NOT_FOUND = 5;
MANGOS_SD2DB_NOT_FOUND = 6;

LAST_UPDATE_APPLIED_RETRIEVAL_ERROR = 7;
LAST_YTDB_FIX_RETRIEVAL_ERROR = 8;