var internetExplorer=document.selection&&window.ActiveXObject&&/MSIE/.test(navigator.userAgent),webkit=/AppleWebKit/.test(navigator.userAgent),safari=/Apple Computer, Inc/.test(navigator.vendor),gecko=navigator.userAgent.match(/gecko\/(\d{8})/i);gecko&&(gecko=Number(gecko[1]));var mac=/Mac/.test(navigator.platform),brokenOpera=window.opera&&/Version\/10.[56]/.test(navigator.userAgent),slowWebkit=/AppleWebKit\/533/.test(navigator.userAgent);
function makeWhiteSpace(i){for(var l=[],m=true;i>0;i--)l.push(m||i==1?nbsp:" "),m^=1;return l.join("")}function fixSpaces(i){i.charAt(0)==" "&&(i=nbsp+i.slice(1));return i.replace(/\t/g,function(){return makeWhiteSpace(indentUnit)}).replace(/[ \u00a0]{2,}/g,function(i){return makeWhiteSpace(i.length)})}function cleanText(i){return i.replace(/\u00a0/g," ").replace(/\u200b/g,"")}
function makePartSpan(i){var l=i;i.nodeType==3?l=i.nodeValue:i=document.createTextNode(l);var m=document.createElement("span");m.isPart=true;m.appendChild(i);m.currentText=l;return m}function alwaysZero(){return 0}var webkitLastLineHack=webkit?function(i){var l=i.lastChild;if(!l||!l.hackBR)l=document.createElement("br"),l.hackBR=true,i.appendChild(l)}:function(){};
function asEditorLines(i){var l=makeWhiteSpace(indentUnit);return map(i.replace(/\t/g,l).replace(/\u00a0/g," ").replace(/\r\n?/g,"\n").split("\n"),fixSpaces)}
var Editor=function(){function i(a,b){function c(a,g){if(a.nodeType==3)(a.nodeValue=fixSpaces(a.nodeValue.replace(/[\r\u200b]/g,"").replace(/\n/g," "))).length&&(f=false),d.push(a);else if(isBR(a)&&a.childNodes.length==0)f=true,d.push(a);else{for(var h=a.firstChild;h;h=h.nextSibling)c(h);!f&&t.hasOwnProperty(a.nodeName.toUpperCase())&&(f=true,(!b||!g)&&d.push(document.createElement("br")))}}var d=[],f=true;c(a,true);return d}function l(a){function b(a){var b=a.parentNode,c=a.nextSibling;return function(a){b.insertBefore(a,
c)}}var c=[],d=null,f=true;return{next:function(){if(!a)throw StopIteration;var e=a;a=e.nextSibling;var g;e.isPart&&e.childNodes.length==1&&e.firstChild.nodeType==3?(g=e.firstChild.nodeValue,e.dirty=e.dirty||g!=e.currentText,e.currentText=g,g=!/[\n\t\r]/.test(e.currentText)):g=false;if(g)return c.push(e),f=false,e.currentText;else if(isBR(e))return f&&window.opera&&e.parentNode.insertBefore(makePartSpan(""),e),c.push(e),f=true,"\n";else{g=!e.nextSibling;d=b(e);removeElement(e);e=i(e,g);for(g=0;g<
e.length;g++){var h=e,u=g,j=e[g],s="\n";j.nodeType==3?(select.snapshotChanged(),j=makePartSpan(j),s=j.currentText,f=false):(f&&window.opera&&d(makePartSpan("")),f=true);j.dirty=true;c.push(j);d(j);h[u]=s}return e.join("")}},nodes:c}}function m(a){for(;a&&!isBR(a);)a=a.previousSibling;return a}function p(a,b){if(a){if(isBR(a))a=a.nextSibling}else a=b.firstChild;for(;a&&!isBR(a);)a=a.nextSibling;return a}function q(a,b,c,d){function f(b){b=cleanText(a.history.textAfter(b));return d?b.toLowerCase():
b}this.editor=a;this.history=a.history;this.history.commit();this.valid=!!b;this.atOccurrence=false;d==void 0&&(d=typeof b=="string"&&b==b.toLowerCase());var e={node:null,offset:0},g=this;c&&typeof c=="object"&&typeof c.character=="number"?(a.checkLine(c.line),c={node:c.line,offset:c.character},this.pos={from:c,to:c}):this.pos=c?{from:select.cursorPos(a.container,true)||e,to:select.cursorPos(a.container,false)||e}:{from:e,to:e};if(typeof b!="string")this.matches=function(a,c,d){if(a)for(var a=f(c).slice(0,
d),e=a.match(b),d=0;e;){var h=a.indexOf(e[0]);d+=h;a=a.slice(h+1);if(h=a.match(b))e=h;else break}else a=f(c).slice(d),d=(e=a.match(b))&&d+a.indexOf(e[0]);if(e)return g.currentMatch=e,{from:{node:c,offset:d},to:{node:c,offset:d+e[0].length}}};else{d&&(b=b.toLowerCase());var h=b.split("\n");this.matches=h.length==1?function(a,c,d){var e=f(c),g=b.length,h;if(a?d>=g&&(h=e.lastIndexOf(b,d-g))!=-1:(h=e.indexOf(b,d))!=-1)return{from:{node:c,offset:h},to:{node:c,offset:h+g}}}:function(a,b,c){var d=a?h.length-
1:0,e=h[d],g=f(b),i=a?g.indexOf(e)+e.length:g.lastIndexOf(e);if(!(a?i>=c||i!=e.length:i<=c||i!=g.length-e.length))for(c=b;;){if(a&&!c)break;c=a?this.history.nodeBefore(c):this.history.nodeAfter(c);if(!a&&!c)break;g=f(c);e=h[a?--d:++d];if(d>0&&d<h.length-1)if(g!=e)break;else continue;d=a?g.lastIndexOf(e):g.indexOf(e)+e.length;if(a?d!=g.length-e.length:d!=e.length)break;return{from:{node:a?c:b,offset:a?d:i},to:{node:a?b:c,offset:a?i:d}}}}}}function o(a){this.options=a;window.indentUnit=a.indentUnit;
var b=this.container=document.body;this.history=new UndoHistory(b,a.undoDepth,a.undoDelay,this);var c=this;if(!o.Parser)throw"No parser loaded.";a.parserConfig&&o.Parser.configure&&o.Parser.configure(a.parserConfig);!a.readOnly&&!internetExplorer&&select.setCursorPos(b,{node:null,offset:0});this.dirty=[];this.importCode(a.content||"");this.history.onChange=a.onChange;if(a.readOnly){if(!a.textWrapping)b.style.whiteSpace="nowrap"}else{if(a.continuousScanning!==false)this.scanner=this.documentScanner(a.passTime),
this.delayScanning();var d=function(){document.body.contentEditable!=void 0&&internetExplorer?document.body.contentEditable="true":document.designMode="on";if(internetExplorer&&a.height!="dynamic")document.body.style.minHeight=window.frameElement.clientHeight-2*document.body.offsetTop-5+"px";document.documentElement.style.borderWidth="0";if(!a.textWrapping)b.style.whiteSpace="nowrap"};try{d()}catch(f){var e=addEventHandler(document,"focus",function(){e();d()},true)}addEventHandler(document,"keydown",
method(this,"keyDown"));addEventHandler(document,"keypress",method(this,"keyPress"));addEventHandler(document,"keyup",method(this,"keyUp"));var g=function(){c.cursorActivity(false)};addEventHandler(internetExplorer?document.body:window,"mouseup",g);addEventHandler(document.body,"cut",g);gecko&&addEventHandler(window,"pagehide",function(){c.unloaded=true});addEventHandler(document.body,"paste",function(a){g();var b=null;try{var d=a.clipboardData||window.clipboardData;d&&(b=d.getData("Text"))}catch(e){}b!==
null&&(a.stop(),c.replaceSelection(b),select.scrollToCursor(c.container))});this.options.autoMatchParens&&addEventHandler(document.body,"click",method(this,"scheduleParenHighlight"))}}var t={P:true,DIV:true,LI:true};q.prototype={findNext:function(){return this.find(false)},findPrevious:function(){return this.find(true)},find:function(a){function b(){var a={node:f,offset:e};c.pos={from:a,to:a};return c.atOccurrence=false}if(!this.valid)return false;var c=this,d=a?this.pos.from:this.pos.to,f=d.node,
e=d.offset;f&&!f.parentNode&&(f=null,e=0);for(;;){if(this.pos=this.matches(a,f,e))return this.atOccurrence=true;if(a){if(!f)return b();f=this.history.nodeBefore(f);e=this.history.textAfter(f).length}else{d=this.history.nodeAfter(f);if(!d)return e=this.history.textAfter(f).length,b();f=d;e=0}}},select:function(){this.atOccurrence&&(select.setCursorPos(this.editor.container,this.pos.from,this.pos.to),select.scrollToCursor(this.editor.container))},replace:function(a){if(this.atOccurrence){var b=this.currentMatch;
b&&(a=a.replace(/\\(\d)/,function(a,d){return b[d]}));this.pos.to=this.editor.replaceRange(this.pos.from,this.pos.to,a);this.atOccurrence=false}},position:function(){if(this.atOccurrence)return{line:this.pos.from.node,character:this.pos.from.offset}}};o.prototype={importCode:function(a){var b=asEditorLines(a);if(!this.options.incrementalLoading||b.length<1E3)this.history.push(null,null,b),this.history.reset();else{var c=0,d=this,f=function(){var a=b.slice(c,c+1E3);a.push("");d.history.push(d.history.nodeBefore(null),
null,a);d.history.reset();c+=1E3;c<b.length&&parent.setTimeout(f,1E3)};f()}},getCode:function(){if(!this.container.firstChild)return"";var a=[];select.markSelection();forEach(l(this.container.firstChild),method(a,"push"));select.selectMarked();webkit&&this.container.lastChild.hackBR&&a.pop();webkitLastLineHack(this.container);return cleanText(a.join(""))},checkLine:function(a){if(a===false||!(a==null||a.parentNode==this.container||a.hackBR))throw parent.CodeMirror.InvalidLineHandle;},cursorPosition:function(a){a==
null&&(a=true);return(a=select.cursorPos(this.container,a))?{line:a.node,character:a.offset}:{line:null,character:0}},firstLine:function(){return null},lastLine:function(){var a=this.container.lastChild;a&&(a=m(a));a&&a.hackBR&&(a=m(a.previousSibling));return a},nextLine:function(a){this.checkLine(a);a=p(a,this.container);return!a||a.hackBR?false:a},prevLine:function(a){this.checkLine(a);return a==null?false:m(a.previousSibling)},visibleLineCount:function(){for(var a=this.container.firstChild;a&&
isBR(a);)a=a.nextSibling;return!a?false:Math.floor((window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight)/a.offsetHeight)},selectLines:function(a,b,c,d){this.checkLine(a);a={node:a,offset:b};b=null;d!==void 0&&(this.checkLine(c),b={node:c,offset:d});select.setCursorPos(this.container,a,b);select.scrollToCursor(this.container)},lineContent:function(a){for(var b=[],a=a?a.nextSibling:this.container.firstChild;a&&!isBR(a);a=a.nextSibling)b.push(nodeText(a));return cleanText(b.join(""))},
setLineContent:function(a,b){this.history.commit();this.replaceRange({node:a,offset:0},{node:a,offset:this.history.textAfter(a).length},b);this.addDirtyNode(a);this.scheduleHighlight()},removeLine:function(a){for(var b=a?a.nextSibling:this.container.firstChild;b;){var c=b.nextSibling;removeElement(b);if(isBR(b))break;b=c}this.addDirtyNode(a);this.scheduleHighlight()},insertIntoLine:function(a,b,c){var d=null;if(b=="end")d=p(a,this.container);else for(var f=a?a.nextSibling:this.container.firstChild;f;f=
f.nextSibling){if(b==0){d=f;break}var e=nodeText(f);if(e.length>b){d=f.nextSibling;c=e.slice(0,b)+c+e.slice(b);removeElement(f);break}b-=e.length}b=asEditorLines(c);for(c=0;c<b.length;c++)c>0&&this.container.insertBefore(document.createElement("BR"),d),this.container.insertBefore(makePartSpan(b[c]),d);this.addDirtyNode(a);this.scheduleHighlight()},selectedText:function(){var a=this.history;a.commit();var b=select.cursorPos(this.container,true),c=select.cursorPos(this.container,false);if(!b||!c)return"";
if(b.node==c.node)return a.textAfter(b.node).slice(b.offset,c.offset);for(var d=[a.textAfter(b.node).slice(b.offset)],b=a.nodeAfter(b.node);b!=c.node;b=a.nodeAfter(b))d.push(a.textAfter(b));d.push(a.textAfter(c.node).slice(0,c.offset));return cleanText(d.join("\n"))},replaceSelection:function(a){this.history.commit();var b=select.cursorPos(this.container,true),c=select.cursorPos(this.container,false);b&&c&&(c=this.replaceRange(b,c,a),select.setCursorPos(this.container,c),webkitLastLineHack(this.container))},
cursorCoords:function(a,b){function c(a,c){var d=-(document.body.scrollTop||document.documentElement.scrollTop||0),e=-(document.body.scrollLeft||document.documentElement.scrollLeft||0)+c;forEach([a,b?null:window.frameElement],function(a){for(;a;)e+=a.offsetLeft,d+=a.offsetTop,a=a.offsetParent});return{x:e,y:d,yBot:d+a.offsetHeight}}function d(a,b){var c=document.createElement("SPAN");c.appendChild(document.createTextNode(a));try{return b(c)}finally{c.parentNode&&c.parentNode.removeChild(c)}}var f=
select.cursorPos(this.container,a);if(!f)return null;for(var e=f.offset,g=f.node,h=this;e;){g=g?g.nextSibling:this.container.firstChild;f=nodeText(g);if(e<f.length)return d(f.substr(0,e),function(a){a.style.position="absolute";a.style.visibility="hidden";a.className=g.className;h.container.appendChild(a);return c(g,a.offsetWidth)});e-=f.length}return g&&isSpan(g)?c(g,g.offsetWidth):g&&g.nextSibling&&isSpan(g.nextSibling)?c(g.nextSibling,0):d("\u200b",function(a){g?g.parentNode.insertBefore(a,g.nextSibling):
h.container.insertBefore(a,h.container.firstChild);return c(a,0)})},reroutePasteEvent:function(){if(!this.capturingPaste&&!(window.opera||gecko&&gecko>=20101026)){this.capturingPaste=true;var a=window.frameElement.CodeMirror.textareaHack,b=this.cursorCoords(true,true);a.style.top=b.y+"px";if(internetExplorer&&(b=select.getBookmark(this.container)))this.selectionSnapshot=b;parent.focus();a.value="";a.focus();var c=this;parent.setTimeout(function(){c.capturingPaste=false;window.focus();c.selectionSnapshot&&
window.select.setBookmark(c.container,c.selectionSnapshot);var b=a.value;b&&(c.replaceSelection(b),select.scrollToCursor(c.container))},10)}},replaceRange:function(a,b,c){c=asEditorLines(c);c[0]=this.history.textAfter(a.node).slice(0,a.offset)+c[0];var d=c[c.length-1];c[c.length-1]=d+this.history.textAfter(b.node).slice(b.offset);b=this.history.nodeAfter(b.node);this.history.push(a.node,b,c);return{node:this.history.nodeBefore(b),offset:d.length}},getSearchCursor:function(a,b,c){return new q(this,
a,b,c)},reindent:function(){this.container.firstChild&&this.indentRegion(null,this.container.lastChild)},reindentSelection:function(a){if(select.somethingSelected()){var b=select.selectionTopNode(this.container,true),c=select.selectionTopNode(this.container,false);b===false||c===false||this.indentRegion(b,c,a,true)}else this.indentAtCursor(a)},grabKeys:function(a,b){this.frozen=a;this.keyFilter=b},ungrabKeys:function(){this.frozen="leave"},setParser:function(a,b){o.Parser=window[a];(b=b||this.options.parserConfig)&&
o.Parser.configure&&o.Parser.configure(b);this.container.firstChild&&(forEach(this.container.childNodes,function(a){if(a.nodeType!=3)a.dirty=true}),this.addDirtyNode(this.firstChild),this.scheduleHighlight())},keyDown:function(a){if(this.frozen=="leave")this.keyFilter=this.frozen=null;if(this.frozen&&(!this.keyFilter||this.keyFilter(a.keyCode,a)))a.stop(),this.frozen(a);else{var b=a.keyCode;this.delayScanning();this.options.autoMatchParens&&this.scheduleParenHighlight();if(b==13)a.ctrlKey&&!a.altKey?
this.reparseBuffer():(select.insertNewlineAtCursor(),b=this.options.enterMode,b!="flat"&&this.indentAtCursor(b=="keep"?"keep":void 0),select.scrollToCursor(this.container)),a.stop();else if(b==9&&this.options.tabMode!="default"&&!a.ctrlKey)this.handleTab(!a.shiftKey),a.stop();else if(b==32&&a.shiftKey&&this.options.tabMode=="default")this.handleTab(true),a.stop();else if(b==36&&!a.shiftKey&&!a.ctrlKey)this.home()&&a.stop();else if(b==35&&!a.shiftKey&&!a.ctrlKey)this.end()&&a.stop();else if(b==33&&
!a.shiftKey&&!a.ctrlKey&&!gecko)this.pageUp()&&a.stop();else if(b==34&&!a.shiftKey&&!a.ctrlKey&&!gecko)this.pageDown()&&a.stop();else if((b==219||b==221)&&a.ctrlKey&&!a.altKey)this.highlightParens(a.shiftKey,true),a.stop();else if(a.metaKey&&!a.shiftKey&&(b==37||b==39)){var c=select.selectionTopNode(this.container);c!==false&&this.container.firstChild&&(b==37?select.focusAfterNode(m(c),this.container):(b=p(c,this.container),select.focusAfterNode(b?b.previousSibling:this.container.lastChild,this.container)),
a.stop())}else if((a.ctrlKey||a.metaKey)&&!a.altKey)a.shiftKey&&b==90||b==89?(select.scrollToNode(this.history.redo()),a.stop()):b==90||safari&&b==8?(select.scrollToNode(this.history.undo()),a.stop()):b==83&&this.options.saveFunction?(this.options.saveFunction(),a.stop()):b==86&&!mac&&this.reroutePasteEvent()}},keyPress:function(a){var b=this.options.electricChars&&o.Parser.electricChars,c=this;if(this.frozen&&(!this.keyFilter||this.keyFilter(a.keyCode||a.code,a))||a.code==13||a.code==9&&this.options.tabMode!=
"default"||a.code==32&&a.shiftKey&&this.options.tabMode=="default")a.stop();else if(mac&&(a.ctrlKey||a.metaKey)&&a.character=="v")this.reroutePasteEvent();else if(b&&b.indexOf(a.character)!=-1)parent.setTimeout(function(){c.indentAtCursor(null)},0);else if(brokenOpera)if(a.code==8){var d=select.selectionTopNode(this.container),c=this,f=d?d.nextSibling:this.container.firstChild;d!==false&&f&&isBR(f)&&parent.setTimeout(function(){select.selectionTopNode(c.container)==f&&select.focusAfterNode(f.previousSibling,
c.container)},20)}else a.code==46&&(d=select.selectionTopNode(this.container),c=this,d&&isBR(d)&&parent.setTimeout(function(){select.selectionTopNode(c.container)!=d&&select.focusAfterNode(d,c.container)},20));else if(slowWebkit&&(f=(d=select.selectionTopNode(this.container))?d.nextSibling:this.container.firstChild,d&&f&&isBR(f)&&!isBR(d))){var e=document.createTextNode("\u200b");this.container.insertBefore(e,f);parent.setTimeout(function(){e.nodeValue=="\u200b"?removeElement(e):e.nodeValue=e.nodeValue.replace("\u200b",
"")},20)}webkit&&!this.options.textWrapping&&setTimeout(function(){var a=select.selectionTopNode(c.container,true);a&&a.nodeType==3&&a.previousSibling&&isBR(a.previousSibling)&&a.nextSibling&&isBR(a.nextSibling)&&a.parentNode.replaceChild(document.createElement("BR"),a.previousSibling)},50)},keyUp:function(a){this.cursorActivity(a.keyCode>=16&&a.keyCode<=18||a.keyCode>=33&&a.keyCode<=40)},indentLineAfter:function(a,b){function c(a){a=a?a.nextSibling:d.container.firstChild;return!a||!hasClass(a,"whitespace")?
null:a}var d=this,f=c(a),e=0,g=f?f.currentText.length:0,h=f?f.nextSibling:a?a.nextSibling:this.container.firstChild;if(b=="keep"){if(a){var i=c(m(a.previousSibling));if(i)e=i.currentText.length}}else i=a&&h&&h.currentText?h.currentText:"",b!=null&&this.options.tabMode!="indent"?e=b?g+indentUnit:Math.max(0,g-indentUnit):a?e=a.indentation(i,g,b,h):o.Parser.firstIndentation&&(e=o.Parser.firstIndentation(i,g,b,h));g=e-g;g<0?e==0?(h&&select.snapshotMove(f.firstChild,h.firstChild||h,0),removeElement(f),
f=null):(select.snapshotMove(f.firstChild,f.firstChild,g,true),f.currentText=makeWhiteSpace(e),f.firstChild.nodeValue=f.currentText):g>0?f?(f.currentText=makeWhiteSpace(e),f.firstChild.nodeValue=f.currentText,select.snapshotMove(f.firstChild,f.firstChild,g,true)):(f=makePartSpan(makeWhiteSpace(e)),f.className="whitespace",a?insertAfter(f,a):this.container.insertBefore(f,this.container.firstChild),select.snapshotMove(h&&(h.firstChild||h),f.firstChild,e,false,true)):f&&select.snapshotMove(f.firstChild,
f.firstChild,e,false);g!=0&&this.addDirtyNode(a)},highlightAtCursor:function(){var a=select.selectionTopNode(this.container,true),b=select.selectionTopNode(this.container,false);if(a===false||b===false)return false;select.markSelection();if(this.highlight(a,p(b,this.container),true,20)===false)return false;select.selectMarked();return true},handleTab:function(a){this.options.tabMode=="spaces"&&!select.somethingSelected()?select.insertTabAtCursor():this.reindentSelection(a)},home:function(){var a=
select.selectionTopNode(this.container,true),b=a;if(a===false||a&&!a.isPart&&!isBR(a)||!this.container.firstChild)return false;for(;a&&!isBR(a);)a=a.previousSibling;var c=a?a.nextSibling:this.container.firstChild;c&&c!=b&&c.isPart&&hasClass(c,"whitespace")?select.focusAfterNode(c,this.container):select.focusAfterNode(a,this.container);select.scrollToCursor(this.container);return true},end:function(){var a=select.selectionTopNode(this.container,true);if(a===false)return false;a=p(a,this.container);
if(!a)return false;select.focusAfterNode(a.previousSibling,this.container);select.scrollToCursor(this.container);return true},pageUp:function(){var a=this.cursorPosition().line,b=this.visibleLineCount();if(a===false||b===false)return false;b-=2;for(var c=0;c<b;c++)if(a=this.prevLine(a),a===false)break;if(c==0)return false;select.setCursorPos(this.container,{node:a,offset:0});select.scrollToCursor(this.container);return true},pageDown:function(){var a=this.cursorPosition().line,b=this.visibleLineCount();
if(a===false||b===false)return false;b-=2;for(var c=0;c<b;c++){var d=this.nextLine(a);if(d===false)break;a=d}if(c==0)return false;select.setCursorPos(this.container,{node:a,offset:0});select.scrollToCursor(this.container);return true},scheduleParenHighlight:function(){this.parenEvent&&parent.clearTimeout(this.parenEvent);var a=this;this.parenEvent=parent.setTimeout(function(){a.highlightParens()},300)},highlightParens:function(a,b){function c(a,b){if(a)h?h.call?h(a,b):a.className+=" "+h[b?0:1]:(a.style.fontWeight=
"bold",a.style.color=b?"#8F8":"#F88")}function d(a){if(a)h&&!h.call?removeClass(removeClass(a,h[0]),h[1]):g.options.unmarkParen?g.options.unmarkParen(a):(a.style.fontWeight="",a.style.color="")}function f(a){if(a.currentText)return(a=a.currentText.match(/^[\s\u00a0]*([\(\)\[\]{}])[\s\u00a0]*$/))&&a[1]}function e(){for(var a=[],b,c=true,d=j;d;d=m?d.nextSibling:d.previousSibling)if(d.className==l&&isSpan(d)&&(b=f(d))){if(/[\(\[\{]/.test(b)==m?a.push(b):a.length?a.pop()!=matching[b]&&(c=false):c=false,
!a.length)break}else if(d.dirty||!isSpan(d)&&!isBR(d))return{node:d,status:"dirty"};return{node:d,status:d&&c}}var g=this,h=this.options.markParen;typeof h=="string"&&(h=[h,h]);!b&&g.highlighted&&(d(g.highlighted[0]),d(g.highlighted[1]));if(window&&window.parent&&window.select){this.parenEvent&&parent.clearTimeout(this.parenEvent);this.parenEvent=null;var i,j=select.selectionTopNode(this.container,true);if(j&&this.highlightAtCursor()&&(j=select.selectionTopNode(this.container,true))&&((i=f(j))||(j=
j.nextSibling)&&(i=f(j))))for(var l=j.className,m=/[\(\[\{]/.test(i);;){var n=e();if(n.status=="dirty")this.highlight(n.node,p(n.node)),n.node.dirty=false;else{c(j,n.status);c(n.node,n.status);b?parent.setTimeout(function(){d(j);d(n.node)},500):g.highlighted=[j,n.node];a&&n.node&&select.focusAfterNode(n.node.previousSibling,this.container);break}}}},indentAtCursor:function(a){if(this.container.firstChild&&this.highlightAtCursor()){var b=select.selectionTopNode(this.container,false);b!==false&&(select.markSelection(),
this.indentLineAfter(m(b),a),select.selectMarked())}},indentRegion:function(a,b,c,d){var f=a=m(a),e=a&&m(a.previousSibling);isBR(b)||(b=p(b,this.container));this.addDirtyNode(a);do{var g=p(f,this.container);f&&this.highlight(e,g,true);this.indentLineAfter(f,c);e=f;f=g}while(f!=b);d&&select.setCursorPos(this.container,{node:a,offset:0},{node:b,offset:0})},cursorActivity:function(a){if(this.unloaded)window.document.designMode="off",window.document.designMode="on",this.unloaded=false;if(internetExplorer){this.container.createTextRange().execCommand("unlink");
clearTimeout(this.saveSelectionSnapshot);var b=this;this.saveSelectionSnapshot=setTimeout(function(){var a=select.getBookmark(b.container);if(a)b.selectionSnapshot=a},200)}var c=this.options.onCursorActivity;if(!a||c){var d=select.selectionTopNode(this.container,false);d!==false&&this.container.firstChild&&(d=d||this.container.firstChild,c&&c(d),a||(this.scheduleHighlight(),this.addDirtyNode(d)))}},reparseBuffer:function(){forEach(this.container.childNodes,function(a){a.dirty=true});this.container.firstChild&&
this.addDirtyNode(this.container.firstChild)},addDirtyNode:function(a){if(a=a||this.container.firstChild){for(var b=0;b<this.dirty.length;b++)if(this.dirty[b]==a)return;if(a.nodeType!=3)a.dirty=true;this.dirty.push(a)}},allClean:function(){return!this.dirty.length},scheduleHighlight:function(){var a=this;parent.clearTimeout(this.highlightTimeout);this.highlightTimeout=parent.setTimeout(function(){a.highlightDirty()},this.options.passDelay)},getDirtyNode:function(){for(;this.dirty.length>0;){var a=
this.dirty.pop();try{for(;a&&a.parentNode!=this.container;)a=a.parentNode;if(a&&(a.dirty||a.nodeType==3))return a}catch(b){}}return null},highlightDirty:function(a){if(!window||!window.parent||!window.select)return false;this.options.readOnly||select.markSelection();for(var b,c=a?null:(new Date).getTime()+this.options.passTime;((new Date).getTime()<c||a)&&(b=this.getDirtyNode());){var d=this.highlight(b,c);d&&d.node&&d.dirty&&this.addDirtyNode(d.node.nextSibling)}this.options.readOnly||select.selectMarked();
b&&this.scheduleHighlight();return this.dirty.length==0},documentScanner:function(a){var b=this,c=null;return function(){if(window&&window.parent&&window.select){c&&c.parentNode!=b.container&&(c=null);select.markSelection();var d=b.highlight(c,(new Date).getTime()+a,true);select.selectMarked();d=d?d.node&&d.node.nextSibling:null;c=c==d?null:d;b.delayScanning()}}},delayScanning:function(){if(this.scanner)parent.clearTimeout(this.documentScan),this.documentScan=parent.setTimeout(this.scanner,this.options.continuousScanning)},
highlight:function(a,b,c,d){function f(a){if(a){var b=a.oldNextSibling;(n||b===void 0||a.nextSibling!=b)&&g.history.touch(a);a.oldNextSibling=a.nextSibling}else b=g.container.oldFirstChild,(n||b===void 0||g.container.firstChild!=b)&&g.history.touch(null),g.container.oldFirstChild=g.container.firstChild}var e=this.container,g=this,h=this.options.activeTokens,i=typeof b=="number"?b:null;if(!e.firstChild)return false;for(;a&&(!a.parserFromHere||a.dirty);){if(d!=null&&isBR(a)&&--d<0)return false;a=a.previousSibling}if(a&&
!a.nextSibling)return false;var j=l(a?a.nextSibling:e.firstChild),d=stringStream(j),m=a?a.parserFromHere(d):o.Parser.make(d),p={current:null,get:function(){if(!this.current)this.current=j.nodes.shift();return this.current},next:function(){this.current=null},remove:function(){e.removeChild(this.get());this.current=null},getNonEmpty:function(){for(var a=this.get();a&&isSpan(a)&&a.currentText=="";)if(window.opera&&(a.previousSibling==null||isBR(a.previousSibling))&&(a.nextSibling==null||isBR(a.nextSibling)))this.next(),
a=this.get();else{var b=a;this.remove();a=this.get();select.snapshotMove(b.firstChild,a&&(a.firstChild||a),0)}return a}},n=false,q=true,r=0;forEach(m,function(d){var k=p.getNonEmpty();if(d.value=="\n"){if(!isBR(k))throw"Parser out of sync. Expected BR.";if(k.dirty||!k.indentation)n=true;f(a);a=k;k.parserFromHere=m.copy();k.indentation=d.indentation||alwaysZero;k.dirty=false;if(i==null&&k==b)throw StopIteration;if(i!=null&&(new Date).getTime()>=i||!n&&!q&&r>1&&!c)throw StopIteration;q=n;n=false;r=
0;p.next()}else{if(!isSpan(k))throw"Parser out of sync. Expected SPAN.";k.dirty&&(n=true);r++;if(!k.reduced&&k.currentText==d.value&&k.className==d.style)h&&k.dirty&&h(k,d,g),k.dirty=false,p.next();else{n=true;var j=makePartSpan(d.value);j.className=d.style;e.insertBefore(j,k);h&&h(j,d,g);for(var d=d.value.length,l=0;d>0;){var k=p.get(),o=k.currentText.length;select.snapshotReplaceNode(k.firstChild,j.firstChild,d,l);o>d?(k.currentText=k.currentText.substring(d),k.reduced=true,d=0):(d-=o,l+=o,p.remove())}}}});
f(a);webkitLastLineHack(this.container);return{node:p.getNonEmpty(),dirty:n}}};return o}();addEventHandler(window,"load",function(){var i=window.frameElement.CodeMirror;i.editor=new Editor(i.options);parent.setTimeout(method(i,"init"),0)});

var select={};
(function(){function l(a,b){for(;a&&a.parentNode!=b;)a=a.parentNode;return a}function s(a,b){for(;!a.previousSibling&&a.parentNode!=b;)a=a.parentNode;return l(a.previousSibling,b)}function p(a){var b=a.nextSibling;if(b){for(;b.firstChild;)b=b.firstChild;return b.nodeType==3||isBR(b)?b:p(b)}else{for(a=a.parentNode;a&&!a.nextSibling;)a=a.parentNode;return a&&p(a)}}select.ie_selection=document.selection&&document.selection.createRangeCollection;select.scrollToNode=function(a,b){if(a){for(var c=a,d=document.body,
e=document.documentElement,g=!c.nextSibling||!c.nextSibling.nextSibling||!c.nextSibling.nextSibling.nextSibling,i=0;c&&!c.offsetTop;)i++,c=c.previousSibling;i==0&&(g=false);if(!webkit||!c||!(c.offsetTop==5&&c.offsetLeft==5)){i*=c?c.offsetHeight:0;for(var h=0,n=a?a.offsetWidth:0;c&&c.offsetParent;)i+=c.offsetTop,isBR(c)||(h+=c.offsetLeft),c=c.offsetParent;var c=d.scrollLeft||e.scrollLeft||0,d=d.scrollTop||e.scrollTop||0,f=false,j=window.innerWidth||e.clientWidth||0;if(b||n<j){if(b){var l=select.offsetInNode(a),
q=nodeText(a).length;q&&(h+=n*(l/q))}n=h-c;if(n<0||n>j)c=h,f=true}h=i-d;if(h<0||g||h>(window.innerHeight||e.clientHeight||0)-50)d=g?1E6:i,f=true;f&&window.scrollTo(c,d)}}};select.scrollToCursor=function(a){select.scrollToNode(select.selectionTopNode(a,true)||a.firstChild,true)};var f=null;select.snapshotChanged=function(){if(f)f.changed=true};select.snapshotReplaceNode=function(a,b,c,d){function e(e){if(a==e.node)f.changed=true,c&&e.offset>c?e.offset-=c:(e.node=b,e.offset+=d||0);else if(select.ie_selection&&
e.offset==0&&e.node==p(a))f.changed=true}f&&(e(f.start),e(f.end))};select.snapshotMove=function(a,b,c,d,e){function g(g){if(a==g.node&&(!e||g.offset==0))f.changed=true,g.node=b,g.offset=d?Math.max(0,g.offset+c):c}f&&(g(f.start),g(f.end))};if(select.ie_selection){var j=function(){var a=document.selection;return!a?null:a.createRange?a.createRange():a.createTextRange()},t=function(a){function b(a){for(var b=null;!b&&a;)b=a.nextSibling,a=a.parentNode;return c(b)}function c(a){for(;a&&a.firstChild;)a=
a.firstChild;return{node:a,offset:0}}var d=j();d.collapse(a);a=d.parentElement();if(!isAncestor(document.body,a))return null;if(!a.firstChild)return c(a);var e=d.duplicate();e.moveToElementText(a);e.collapse(true);for(var g=a.firstChild;g;g=g.nextSibling){if(g.nodeType==3){var i=g.nodeValue.length;e.move("character",i)}else e.moveToElementText(g),e.collapse(false);var h=d.compareEndPoints("StartToStart",e);if(h==0)return b(g);if(h!=1){if(g.nodeType!=3)return c(g);e.setEndPoint("StartToEnd",d);return{node:g,
offset:i-e.text.length}}}return b(a)};select.markSelection=function(){f=null;if(document.selection){var a=t(true),b=t(false);a&&b&&(f={start:a,end:b,changed:false})}};select.selectMarked=function(){function a(a){var c=document.body.createTextRange(),b=a.node;if(b)if(b.nodeType==3){c.moveToElementText(b.parentNode);for(a=a.offset;b.previousSibling;)b=b.previousSibling,a+=(b.innerText||"").length;c.move("character",a)}else c.moveToElementText(b),c.collapse(true);else c.moveToElementText(document.body),
c.collapse(false);return c}if(f&&f.changed){var b=a(f.start),c=a(f.end);b.setEndPoint("StartToEnd",c);b.select()}};select.offsetInNode=function(a){var b=j();if(!b)return 0;var c=b.duplicate();try{c.moveToElementText(a)}catch(d){return 0}b.setEndPoint("StartToStart",c);return b.text.length};select.selectionTopNode=function(a,b){var c=j();if(!c)return false;var d=c.duplicate();c.collapse(b);var e=c.parentElement();if(e&&isAncestor(a,e)&&(d.moveToElementText(e),c.compareEndPoints("StartToStart",d)==
1))return l(e,a);b=0;for(e=a.childNodes.length-1;b<e;){var g=Math.ceil((e+b)/2),i=a.childNodes[g];if(!i)return false;var h;a:{h=d;if(i.nodeType==3){for(var f=0,k=i.previousSibling;k&&k.nodeType==3;)f+=k.nodeValue.length,k=k.previousSibling;if(k){try{h.moveToElementText(k)}catch(m){h=false;break a}h.collapse(false)}else h.moveToElementText(i.parentNode);f&&h.move("character",f)}else try{h.moveToElementText(i)}catch(o){h=false;break a}h=true}if(!h)return false;c.compareEndPoints("StartToStart",d)==
1?b=g:e=g-1}if(b==0){c=j();d=c.duplicate();try{d.moveToElementText(a)}catch(q){return null}if(c.compareEndPoints("StartToStart",d)==0)return null}return a.childNodes[b]||null};select.focusAfterNode=function(a,b){var c=document.body.createTextRange();c.moveToElementText(a||b);c.collapse(!a);c.select()};select.somethingSelected=function(){var a=j();return a&&a.text!=""};var u=function(a){var b=j();b&&(b.pasteHTML(a),b.collapse(false),b.select())};select.insertNewlineAtCursor=function(){u("<br>")};select.insertTabAtCursor=
function(){u("\u00a0\u00a0\u00a0\u00a0")};select.cursorPos=function(a,b){var c=j();if(!c)return null;for(var d=select.selectionTopNode(a,b);d&&!isBR(d);)d=d.previousSibling;var e=c.duplicate();c.collapse(b);if(d)e.moveToElementText(d),e.collapse(false);else{try{e.moveToElementText(a)}catch(g){return null}e.collapse(true)}c.setEndPoint("StartToStart",e);return{node:d,offset:c.text.length}};select.setCursorPos=function(a,b,c){function d(c){var b=document.body.createTextRange();c.node?(b.moveToElementText(c.node),
b.collapse(false)):(b.moveToElementText(a),b.collapse(true));b.move("character",c.offset);return b}var e=d(b);c&&c!=b&&e.setEndPoint("EndToEnd",d(c));e.select()};select.getBookmark=function(a){var b=select.cursorPos(a,true),a=select.cursorPos(a,false);if(b&&a)return{from:b,to:a}};select.setBookmark=function(a,b){b&&select.setCursorPos(a,b.from,b.to)}}else{var r=function(a,b){for(;a.nodeType!=3&&!isBR(a);){for(var c=a.childNodes[b]||a.nextSibling,b=0;!c&&a.parentNode;)a=a.parentNode,c=a.nextSibling;
a=c;if(!c)break}return{node:a,offset:b}};select.markSelection=function(){var a=window.getSelection();if(!a||a.rangeCount==0)return f=null;a=a.getRangeAt(0);f={start:r(a.startContainer,a.startOffset),end:r(a.endContainer,a.endOffset),changed:false}};select.selectMarked=function(){function a(){if(c.start.node==c.end.node&&c.start.offset==c.end.offset){var a=window.getSelection();if(!a||a.rangeCount==0)return true;a=a.getRangeAt(0);a=r(a.startContainer,a.startOffset);return c.start.node!=a.node||c.start.offset!=
a.offset}}function b(a,b){if(a.node)if(a.offset==0)d["set"+b+"Before"](a.node);else d["set"+b](a.node,a.offset);else d.setStartAfter(document.body.lastChild||document.body)}var c=f;if(c&&(c.changed||webkit&&a())){var d=document.createRange();b(c.end,"End");b(c.start,"Start");o(d)}};var o=function(a){var b=window.getSelection();b&&(b.removeAllRanges(),b.addRange(a))},m=function(){var a=window.getSelection();return!a||a.rangeCount==0?false:a.getRangeAt(0)};select.selectionTopNode=function(a,b){var c=
m();if(!c)return false;var d=b?c.startContainer:c.endContainer,e=b?c.startOffset:c.endOffset;window.opera&&!b&&c.endContainer==a&&c.endOffset==c.startOffset+1&&a.childNodes[c.startOffset]&&isBR(a.childNodes[c.startOffset])&&e--;return d.nodeType==3?e>0?l(d,a):s(d,a):d.nodeName.toUpperCase()=="HTML"?e==1?null:a.lastChild:d==a?e==0?null:d.childNodes[e-1]:e==d.childNodes.length?l(d,a):e==0?s(d,a):l(d.childNodes[e-1],a)};select.focusAfterNode=function(a,b){var c=document.createRange();c.setStartBefore(b.firstChild||
b);a&&!a.firstChild?c.setEndAfter(a):a?c.setEnd(a,a.childNodes.length):c.setEndBefore(b.firstChild||b);c.collapse(false);o(c)};select.somethingSelected=function(){var a=m();return a&&!a.collapsed};select.offsetInNode=function(a){var b=m();if(!b)return 0;b=b.cloneRange();b.setStartBefore(a);return b.toString().length};select.insertNodeAtCursor=function(a){var b=m();if(b){b.deleteContents();b.insertNode(a);webkitLastLineHack(document.body);if(window.opera&&isBR(a)&&isSpan(a.parentNode)){var b=a.nextSibling,
c=a.parentNode,d=c.parentNode;d.insertBefore(a,c.nextSibling);for(c="";b&&b.nodeType==3;b=b.nextSibling)c+=b.nodeValue,removeElement(b);d.insertBefore(makePartSpan(c,document),a.nextSibling)}b=document.createRange();b.selectNode(a);b.collapse(false);o(b)}};select.insertNewlineAtCursor=function(){select.insertNodeAtCursor(document.createElement("BR"))};select.insertTabAtCursor=function(){select.insertNodeAtCursor(document.createTextNode("\u00a0\u00a0\u00a0\u00a0"))};select.cursorPos=function(a,b){var c=
m();if(c){for(var d=select.selectionTopNode(a,b);d&&!isBR(d);)d=d.previousSibling;c=c.cloneRange();c.collapse(b);d?c.setStartAfter(d):c.setStartBefore(a);return{node:d,offset:c.toString().length}}};select.setCursorPos=function(a,b,c){function d(b,c,d){function f(a){a.nodeType==3?k.push(a):forEach(a.childNodes,f)}if(c==0&&b&&!b.nextSibling)return e["set"+d+"After"](b),true;if(b=b?b.nextSibling:a.firstChild){if(c==0)return e["set"+d+"Before"](b),true;for(var k=[];;){for(;b&&!k.length;)f(b),b=b.nextSibling;
var j=k.shift();if(!j)return false;var l=j.nodeValue.length;if(l>=c)return e["set"+d](j,c),true;c-=l}}}var e=document.createRange(),c=c||b;d(c.node,c.offset,"End")&&d(b.node,b.offset,"Start")&&o(e)}}})();

var stringStream=function(g){function e(){for(;c==a.length;){d+=a;a="";c=0;try{a=g.next()}catch(b){if(b!=StopIteration)throw b;else return false}}return true}var a="",c=0,d="";return{peek:function(){return!e()?null:a.charAt(c)},next:function(){if(!e())if(d.length>0)throw"End of stringstream reached without emptying buffer ('"+d+"').";else throw StopIteration;return a.charAt(c++)},get:function(){var b=d;d="";c>0&&(b+=a.slice(0,c),a=a.slice(c),c=0);return b},push:function(b){a=a.slice(0,c)+b+a.slice(c)},
lookAhead:function(b,h,f,m){function i(b){return m?b.toLowerCase():b}var b=i(b),j=false,e=d,n=c;for(f&&this.nextWhileMatches(/[\s\u00a0]/);;){var f=c+b.length,k=a.length-c;if(f<=a.length){j=b==i(a.slice(c,f));c=f;break}else if(b.slice(0,k)==i(a.slice(c))){d+=a;a="";try{a=g.next()}catch(l){if(l!=StopIteration)throw l;break}c=0;b=b.slice(k)}else break}if(!j||!h)a=d.slice(e.length)+a,c=n,d=e;return j},lookAheadRegex:function(b,h){if(b.source.charAt(0)!="^")throw Error("Regexps passed to lookAheadRegex must start with ^");
for(;a.indexOf("\n",c)==-1;)try{a+=g.next()}catch(d){if(d!=StopIteration)throw d;break}var e=a.slice(c).match(b);e&&h&&(c+=e[0].length);return e},more:function(){return this.peek()!==null},applies:function(b){var a=this.peek();return a!==null&&b(a)},nextWhile:function(b){for(var a;(a=this.peek())!==null&&b(a);)this.next()},matches:function(b){var a=this.peek();return a!==null&&b.test(a)},nextWhileMatches:function(b){for(var a;(a=this.peek())!==null&&b.test(a);)this.next()},equals:function(a){return a===
this.peek()},endOfLine:function(){var a=this.peek();return a==null||a=="\n"}}};

function tokenizer(b,e){function c(a){return a!="\n"&&/^[\s\u00a0]*$/.test(a)}var d={state:e,take:function(a){typeof a=="string"&&(a={style:a,type:a});a.content=(a.content||"")+b.get();/\n$/.test(a.content)||b.nextWhile(c);a.value=a.content+b.get();return a},next:function(){if(!b.more())throw StopIteration;var a;if(b.equals("\n"))return b.next(),this.take("whitespace");if(b.applies(c))a="whitespace";else for(;!a;)a=this.state(b,function(a){d.state=a});return this.take(a)}};return d};

function UndoHistory(a,b,c,g){this.container=a;this.maxDepth=b;this.commitDelay=c;this.editor=g;this.last=this.first=a={text:"",from:null,to:null};this.firstTouched=false;this.history=[];this.redoHistory=[];this.touched=[];this.lostundo=0}
UndoHistory.prototype={scheduleCommit:function(){var a=this;parent.clearTimeout(this.commitTimeout);this.commitTimeout=parent.setTimeout(function(){a.tryCommit()},this.commitDelay)},touch:function(a){this.setTouched(a);this.scheduleCommit()},undo:function(){this.commit();if(this.history.length){var a=this.history.pop();this.redoHistory.push(this.updateTo(a,"applyChain"));this.notifyEnvironment();return this.chainNode(a)}},redo:function(){this.commit();if(this.redoHistory.length){var a=this.redoHistory.pop();
this.addUndoLevel(this.updateTo(a,"applyChain"));this.notifyEnvironment();return this.chainNode(a)}},clear:function(){this.history=[];this.redoHistory=[];this.lostundo=0},historySize:function(){return{undo:this.history.length,redo:this.redoHistory.length,lostundo:this.lostundo}},push:function(a,b,c){for(var g=[],e=0;e<c.length;e++){var f=e==c.length-1?b:document.createElement("br");g.push({from:a,to:f,text:cleanText(c[e])});a=f}this.pushChains([g],a==null&&b==null);this.notifyEnvironment()},pushChains:function(a,
b){this.commit(b);this.addUndoLevel(this.updateTo(a,"applyChain"));this.redoHistory=[]},chainNode:function(a){for(var b=0;b<a.length;b++){var c=a[b][0];if(c=c&&(c.from||c.to))return c}},reset:function(){this.history=[];this.redoHistory=[];this.lostundo=0},textAfter:function(a){return this.after(a).text},nodeAfter:function(a){return this.after(a).to},nodeBefore:function(a){return this.before(a).from},tryCommit:function(){window&&window.parent&&window.UndoHistory&&(this.editor.highlightDirty()?this.commit(true):
this.scheduleCommit())},commit:function(a){parent.clearTimeout(this.commitTimeout);a||this.editor.highlightDirty(true);a=this.touchedChains();if(a.length)this.addUndoLevel(this.updateTo(a,"linkChain")),this.redoHistory=[],this.notifyEnvironment()},updateTo:function(a,b){for(var c=[],g=[],e=0;e<a.length;e++)c.push(this.shadowChain(a[e])),g.push(this[b](a[e]));b=="applyChain"&&this.notifyDirty(g);return c},notifyDirty:function(a){forEach(a,method(this.editor,"addDirtyNode"));this.editor.scheduleHighlight()},
notifyEnvironment:function(){if(this.onChange)this.onChange(this.editor);window.frameElement&&window.frameElement.CodeMirror.updateNumbers&&window.frameElement.CodeMirror.updateNumbers()},linkChain:function(a){for(var b=0;b<a.length;b++){var c=a[b];c.from?c.from.historyAfter=c:this.first=c;c.to?c.to.historyBefore=c:this.last=c}},after:function(a){return a?a.historyAfter:this.first},before:function(a){return a?a.historyBefore:this.last},setTouched:function(a){if(a){if(!a.historyTouched)this.touched.push(a),
a.historyTouched=true}else this.firstTouched=true},addUndoLevel:function(a){this.history.push(a);this.history.length>this.maxDepth&&(this.history.shift(),lostundo+=1)},touchedChains:function(){function a(a){for(var b=[],d=a?a.nextSibling:c.container.firstChild;d&&(!isBR(d)||d.hackBR);d=d.nextSibling)!d.hackBR&&d.currentText&&b.push(d.currentText);return{from:a,to:d,text:cleanText(b.join(""))}}function b(a,c){for(var d=c+"Sibling",b=a[d];b&&!isBR(b);)b=b[d];return b}var c=this,g=null,e=[];c.firstTouched&&
c.touched.push(null);forEach(c.touched,function(b){if(!b||!(b.parentNode!=c.container||b.hackBR)){b?b.historyTouched=false:c.firstTouched=false;var f=a(b),d=c.after(b);if(!d||d.text!=f.text||d.to!=f.to)e.push(f),b?b.historyTemp=f:g=f}});var f=[];c.touched=[];forEach(e,function(e){if(e.from?e.from.historyTemp:g){for(var h=[],d=e.from,j=true;;){var i=d?d.historyTemp:g;if(!i)if(j)break;else i=a(d);h.unshift(i);d?d.historyTemp=null:g=null;if(!d)break;j=c.after(d);d=b(d,"previous")}d=e.to;for(j=c.before(e.from);;){if(!d)break;
i=d?d.historyTemp:g;if(!i)if(j)break;else i=a(d);h.push(i);d?d.historyTemp=null:g=null;j=c.before(d);d=b(d,"next")}f.push(h)}});return f},shadowChain:function(a){for(var b=[],c=this.after(a[0].from),a=a[a.length-1].to;;)if(b.push(c),c=c.to,!c||c==a)break;else c=c.historyAfter||this.before(a);return b},applyChain:function(a){for(var b=select.cursorPos(this.container,false),c=a[0].from,g=a[a.length-1].to,e=c?c.nextSibling:this.container.firstChild;e!=g;){var f=e.nextSibling;removeElement(e);e=f}for(e=
0;e<a.length;e++)if(f=a[e],e>0&&this.container.insertBefore(f.from,g),this.container.insertBefore(makePartSpan(fixSpaces(f.text)),g),b&&b.node==f.from){var k=0,h=this.after(f.from);if(h&&e==a.length-1){for(var d=0;d<b.offset&&f.text.charAt(d)==h.text.charAt(d);d++);b.offset>d&&(k=f.text.length-h.text.length)}select.setCursorPos(this.container,{node:f.from,offset:Math.max(0,b.offset+k)})}else b&&e==a.length-1&&b.node&&b.node.parentNode!=this.container&&select.setCursorPos(this.container,{node:f.from,
offset:f.text.length});this.linkChain(a);return c}};

function method(a,b){return function(){a[b].apply(a,arguments)}}var StopIteration={toString:function(){return"StopIteration"}};function forEach(a,b){if(a.next)try{for(;;)b(a.next())}catch(c){if(c!=StopIteration)throw c;}else for(var d=0;d<a.length;d++)b(a[d])}function map(a,b){var c=[];forEach(a,function(a){c.push(b(a))});return c}function matcher(a){return function(b){return a.test(b)}}function hasClass(a,b){var c=a.className;return c&&RegExp("(^| )"+b+"($| )").test(c)}
function removeClass(a,b){a.className=a.className.replace(RegExp(" "+b+"\\b","g"),"");return a}function insertAfter(a,b){b.parentNode.insertBefore(a,b.nextSibling);return a}function removeElement(a){a.parentNode&&a.parentNode.removeChild(a)}function clearElement(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function isAncestor(a,b){for(;b=b.parentNode;)if(a==b)return true;return false}var nbsp="\u00a0",matching={"{":"}","[":"]","(":")","}":"{","]":"[",")":"("};
function normalizeEvent(a){if(!a.stopPropagation)a.stopPropagation=function(){this.cancelBubble=true},a.preventDefault=function(){this.returnValue=false};if(!a.stop)a.stop=function(){this.stopPropagation();this.preventDefault()};if(a.type=="keypress")a.code=a.charCode==null?a.keyCode:a.charCode,a.character=String.fromCharCode(a.code);return a}
function addEventHandler(a,b,c,d){function e(a){c(normalizeEvent(a||window.event))}if(typeof a.addEventListener=="function"){if(a.addEventListener(b,e,false),d)return function(){a.removeEventListener(b,e,false)}}else if(a.attachEvent("on"+b,e),d)return function(){a.detachEvent("on"+b,e)}}function nodeText(a){return a.textContent||a.innerText||a.nodeValue||""}function nodeTop(a){for(var b=0;a.offsetParent;)b+=a.offsetTop,a=a.offsetParent;return b}
function isBR(a){a=a.nodeName;return a=="BR"||a=="br"}function isSpan(a){a=a.nodeName;return a=="SPAN"||a=="span"};

var SqlParser=Editor.Parser=function(){function j(a){return RegExp("^(?:"+a.join("|")+")$","i")}function f(a){return function(c){c=c&&c.charAt(0);c=a&&c==a.type;return a?a.align?a.col-(c?a.width:0):a.indent+(c?0:indentUnit):0}}var i=j("abs,acos,adddate,aes_encrypt,aes_decrypt,ascii,asin,atan,atan2,avg,benchmark,bin,bit_and,bit_count,bit_length,bit_or,cast,ceil,ceiling,char_length,character_length,coalesce,concat,concat_ws,connection_id,conv,convert,cos,cot,count,curdate,current_date,current_time,current_timestamp,current_user,curtime,database,date_add,date_format,date_sub,dayname,dayofmonth,dayofweek,dayofyear,decode,degrees,des_encrypt,des_decrypt,elt,encode,encrypt,exp,export_set,extract,field,find_in_set,floor,format,found_rows,from_days,from_unixtime,get_lock,greatest,group_unique_users,hex,ifnull,inet_aton,inet_ntoa,instr,interval,is_free_lock,isnull,last_insert_id,lcase,least,left,length,ln,load_file,locate,log,log2,log10,lower,lpad,ltrim,make_set,master_pos_wait,max,md5,mid,min,mod,monthname,now,nullif,oct,octet_length,ord,password,period_add,period_diff,pi,position,pow,power,quarter,quote,radians,rand,release_lock,repeat,reverse,right,round,rpad,rtrim,sec_to_time,session_user,sha,sha1,sign,sin,soundex,space,sqrt,std,stddev,strcmp,subdate,substring,substring_index,sum,sysdate,system_user,tan,time_format,time_to_sec,to_days,trim,ucase,unique_users,unix_timestamp,upper,user,version,week,weekday,yearweek".split(",")),
g=j("alter,grant,revoke,primary,key,table,start,top,transaction,select,update,insert,delete,create,describe,from,into,values,where,join,inner,left,natural,and,or,in,not,xor,like,using,on,order,group,by,asc,desc,limit,offset,union,all,as,distinct,set,commit,rollback,replace,view,database,separator,if,exists,null,truncate,status,show,lock,unique,having,drop,procedure,begin,end,delimiter,call,else,leave,declare,temporary,then,definer,event,schedule,comment,enable,disable,slave".split(",")),n=j("bigint,binary,bit,blob,bool,char,character,date,datetime,dec,decimal,double,enum,float,float4,float8,int,int1,int2,int3,int4,int8,integer,long,longblob,longtext,mediumblob,mediumint,mediumtext,middleint,nchar,numeric,real,set,smallint,text,time,timestamp,tinyblob,tinyint,tinytext,varbinary,varchar,year".split(",")),
h=j(":=,<,<=,==,<>,>,>=,like,rlike,in,xor,between".split(",")),k=/[*+\-<>=&|:\/]/,l={},m=function(){function a(d,a){var b=d.next();if(b=="@"||b=="$")return d.nextWhileMatches(/[\w\d]/),"sql-var";else if(b=="[")return a(c(b)),null;else if(b=='"'||b=="'"||b=="`")return a(f(b)),null;else if(b==","||b==";")return"sql-separator";else if(b=="#"){for(;!d.endOfLine();)d.next();return"sql-comment"}else if(b=="-")if(d.peek()=="-"){for(;!d.endOfLine();)d.next();return"sql-comment"}else return/\d/.test(d.peek())?
(d.nextWhileMatches(/\d/),d.peek()=="."&&(d.next(),d.nextWhileMatches(/\d/)),"sql-number"):"sql-operator";else return k.test(b)?b=="/"&&d.peek()=="*"?(a(e("sql-comment","*/")),null):(d.nextWhileMatches(k),"sql-operator"):/\d/.test(b)?(d.nextWhileMatches(/\d/),d.peek()=="."&&(d.next(),d.nextWhileMatches(/\d/)),"sql-number"):/[()]/.test(b)?"sql-punctuation":(d.nextWhileMatches(/[_\w\d]/),b=d.get(),{style:h.test(b)?"sql-operator":g.test(b)?"sql-keyword":i.test(b)?"sql-function":n.test(b)?"sql-type":
"sql-word",content:b})}function c(){return function(d,c){for(;!d.endOfLine();)if(d.next()=="]"){c(a);break}return"sql-word"}}function f(d){return function(c,b){for(var e=false;!c.endOfLine();){var f=c.next();if(f==d&&!e){b(a);break}e=l.extension=="T-SQL"?!e&&d==f&&c.equals(d):!e&&f=="\\"}return d=="`"?"sql-quoted-word":"sql-literal"}}function e(d,c){return function(b,e){for(;!b.endOfLine();){if(b.lookAhead(c,true)){e(a);break}b.next()}return d}}return function(d,c){return tokenizer(d,c||a)}}();return{make:function(a){function c(c,
b,a){e={prev:e,indent:d,col:g,type:c,width:b,align:a}}var i=m(a),e=null,d=0,g=0,b={next:function(){var b=i.next(),a=b.style,h=b.content,j=b.value.length;if(h=="\n"){if(b.indentation=f(e),d=g=0,e&&e.align==null)e.align=false}else a=="whitespace"&&g==0?d=j:!e&&a!="sql-comment"&&c(";",0,false);h!="\n"&&(g+=j);if(a=="sql-punctuation")if(h=="(")c(")",j);else{if(h==")")e=e.prev}else if(a=="sql-separator"&&h==";"&&e&&!e.prev)e=e.prev;return b},copy:function(){var a=e,c=d,f=g,h=i.state;return function(j){i=
m(j,h);e=a;d=c;g=f;return b}}};return b},electricChars:")",configure:function(a){for(var c in a)a.hasOwnProperty(c)&&(l[c]=a[c])}}}(),StopIteration={toString:function(){return"StopIteration"}},indentUnit=2;
(function(){function j(f){for(var i="",g=0;g<indentUnit;g++)i+=" ";for(var f=f.replace(/\t/g,i).replace(/\u00a0/g," ").replace(/\r\n?/g,"\n"),j=0,h=[],f=f.split("\n"),i=0;i<f.length;i++)i!=0&&h.push("\n"),h.push(f[i]);return{next:function(){if(j<h.length)return h[j++];else throw StopIteration;}}}window.highlightSql=function(f,i,g){parser=(SqlParser||Editor.Parser).make(stringStream(j(g)));var n=1;callback=function(a){i.append(document.createTextNode(String(n++)));i.append(document.createElement("BR"));
for(var c=0;c<a.length;c++)f.append(a[c]);f.append(document.createElement("BR"))};g=[];if(callback.nodeType==1){var h=callback;callback=function(a){for(var c=0;c<a.length;c++)h.appendChild(a[c]);h.appendChild(document.createElement("br"))}}try{for(;;){var k=parser.next();if(k.value=="\n")callback(g),g=[];else{var l=document.createElement("span");l.className=k.style;l.appendChild(document.createTextNode(k.value));g.push(l)}}}catch(m){if(m!=StopIteration)throw m;}g.length&&callback(g)}})();

