/*
 jquery.layout 1.3.0 - Release Candidate 29.8
 $Date: 2010-09-27 08:00:00 (Mon, 27 Sep 2010) $
 $Rev: 30298 $

 Copyright (c) 2010 
 Fabrizio Balliano (http://www.fabrizioballiano.net)
 Kevin Dalman (http://allpro.net)

 Dual licensed under the GPL (http://www.gnu.org/licenses/gpl.html)
 and MIT (http://www.opensource.org/licenses/mit-license.php) licenses.

 Docs: http://layout.jquery-dev.net/documentation.html
 Tips: http://layout.jquery-dev.net/tips.html
 Help: http://groups.google.com/group/jquery-ui-layout
*/
(function(f){var t=f.browser;f.layout={browser:{mozilla:t.mozilla,webkit:t.webkit||t.safari||false,msie:t.msie,isIE6:t.msie&&t.version==6,boxModel:false},scrollbarWidth:function(){return window.scrollbarWidth||f.layout.getScrollbarSize("width")},scrollbarHeight:function(){return window.scrollbarHeight||f.layout.getScrollbarSize("height")},getScrollbarSize:function(h){var o=f('<div style="position: absolute; top: -10000px; left: -10000px; width: 100px; height: 100px; overflow: scroll;"></div>').appendTo("body"),
p={width:o.width()-o[0].clientWidth,height:o.height()-o[0].clientHeight};o.remove();window.scrollbarWidth=p.width;window.scrollbarHeight=p.height;return h.match(/^(width|height)$/i)?p[h]:p},showInvisibly:function(h,o){if(!h)return{};h.jquery||(h=f(h));var p={display:h.css("display"),visibility:h.css("visibility")};return o||p.display=="none"?(h.css({display:"block",visibility:"hidden"}),p):{}},getElemDims:function(h){var o={},p=o.css={},q={},t,z,v=h.offset();o.offsetLeft=v.left;o.offsetTop=v.top;
f.each("Left,Right,Top,Bottom".split(","),function(w,v){t=p["border"+v]=f.layout.borderWidth(h,v);z=p["padding"+v]=f.layout.cssNum(h,"padding"+v);q[v]=t+z;o["inset"+v]=z});o.offsetWidth=h.innerWidth();o.offsetHeight=h.innerHeight();o.outerWidth=h.outerWidth();o.outerHeight=h.outerHeight();o.innerWidth=o.outerWidth-q.Left-q.Right;o.innerHeight=o.outerHeight-q.Top-q.Bottom;p.width=h.width();p.height=h.height();return o},getElemCSS:function(f,o){var p={},q=f[0].style,t=o.split(","),z="Top,Bottom,Left,Right".split(","),
v="Color,Style,Width".split(","),w,F,J,T,Y,U;for(T=0;T<t.length;T++)if(w=t[T],w.match(/(border|padding|margin)$/))for(Y=0;Y<4;Y++)if(F=z[Y],w=="border")for(U=0;U<3;U++)J=v[U],p[w+F+J]=q[w+F+J];else p[w+F]=q[w+F];else p[w]=q[w];return p},cssWidth:function(h,o){var p=f.layout.borderWidth,q=f.layout.cssNum;if(o<=0)return 0;if(!f.layout.browser.boxModel)return o;p=o-p(h,"Left")-p(h,"Right")-q(h,"paddingLeft")-q(h,"paddingRight");return p>0?p:0},cssHeight:function(h,o){var p=f.layout.borderWidth,q=f.layout.cssNum;
if(o<=0)return 0;if(!f.layout.browser.boxModel)return o;p=o-p(h,"Top")-p(h,"Bottom")-q(h,"paddingTop")-q(h,"paddingBottom");return p>0?p:0},cssNum:function(h,o){h.jquery||(h=f(h));var p=f.layout.showInvisibly(h),q=parseInt(f.curCSS(h[0],o,true),10)||0;h.css(p);return q},borderWidth:function(h,o){h.jquery&&(h=h[0]);var p="border"+o.substr(0,1).toUpperCase()+o.substr(1);return f.curCSS(h,p+"Style",true)=="none"?0:parseInt(f.curCSS(h,p+"Width",true),10)||0}};f.fn.layout=function(h){var o,p,q,t,z,v,w,
F,J,T;function Y(a){if(!a)return true;var b=a.keyCode;if(b<33)return true;var c={38:"north",40:"south",37:"west",39:"east"},e=a.shiftKey,d=a.ctrlKey,m,g,i,l;d&&b>=37&&b<=40&&n[c[b]].enableCursorHotkey?l=c[b]:(d||e)&&f.each(j.borderPanes.split(","),function(a,c){m=n[c];g=m.customHotkey;i=m.customHotkeyModifier;if(e&&i=="SHIFT"||d&&i=="CTRL"||d&&e)if(g&&b==(isNaN(g)||g<=9?g.toUpperCase().charCodeAt(0):g))return l=c,false});if(!l||!s[l]||!n[l].closable||k[l].isHidden)return true;Z(l);a.stopPropagation();
return a.returnValue=false}function U(a){this&&this.tagName&&(a=this);var b;G(a)?b=s[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),false});if(b&&b.length){var c=b.data("layoutEdge"),a=k[c];a.cssSaved&&ia(c);if(a.isSliding||a.isResizing||a.isClosed)a.cssSaved=false;else{var e={zIndex:j.zIndex.pane_normal+2},d={},m=b.css("overflow"),g=b.css("overflowX"),i=b.css("overflowY");if(m!="visible")d.overflow=m,e.overflow="visible";if(g&&!g.match(/visible|auto/))d.overflowX=
g,e.overflowX="visible";if(i&&!i.match(/visible|auto/))d.overflowY=g,e.overflowY="visible";a.cssSaved=d;b.css(e);f.each(j.allPanes.split(","),function(a,b){b!=c&&ia(b)})}}}function ia(a){this&&this.tagName&&(a=this);var b;G(a)?b=s[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),false});if(b&&b.length){var a=b.data("layoutEdge"),a=k[a],c=a.cssSaved||{};!a.isSliding&&!a.isResizing&&b.css("zIndex",j.zIndex.pane_normal);b.css(c);a.cssSaved=
false}}function ja(a,b,c){var e=f(a);if(e.length)if(j.borderPanes.indexOf(b)==-1)alert(o+q.toLowerCase()+": "+b);else return a=n[b].buttonClass+"-"+c,e.addClass(a+" "+a+"-"+b).data("layoutName",n.name),e;else alert(o+p+": "+a);return null}function Ca(a,b,c){switch(b.toLowerCase()){case "toggle":oa(a,c);break;case "open":pa(a,c);break;case "close":Da(a,c);break;case "pin":Ea(a,c);break;case "toggle-slide":oa(a,c,true);break;case "open-slide":pa(a,c,true)}}function oa(a,b,c){(a=ja(a,b,"toggle"))&&a.click(function(a){Z(b,
!!c);a.stopPropagation()})}function pa(a,b,c){(a=ja(a,b,"open"))&&a.attr("title",t).click(function(a){O(b,!!c);a.stopPropagation()})}function Da(a,b){var c=ja(a,b,"close");c&&c.attr("title",z).click(function(a){K(b);a.stopPropagation()})}function Ea(a,b){var c=ja(a,b,"pin");if(c){var e=k[b];c.click(function(a){qa(f(this),b,e.isSliding||e.isClosed);e.isSliding||e.isClosed?O(b):K(b);a.stopPropagation()});qa(c,b,!e.isClosed&&!e.isSliding);j[b].pins.push(a)}}function ra(a,b){f.each(j[a].pins,function(c,
e){qa(f(e),a,b)})}function qa(a,b,c){var e=a.attr("pin");if(!(e&&c==(e=="down"))){var e=n[b].buttonClass+"-pin",d=e+"-"+b,b=e+"-up "+d+"-up",e=e+"-down "+d+"-down";a.attr("pin",c?"down":"up").attr("title",c?v:w).removeClass(c?b:e).addClass(c?e:b)}}function Fa(a){for(var a=f.extend({},n.cookie,a||{}).name||n.name||"Layout",b=document.cookie,b=b?b.split(";"):[],c,e=0,d=b.length;e<d;e++)if(c=f.trim(b[e]).split("="),c[0]==a)return Ga(decodeURIComponent(c[1]));return""}function sa(a,b){var c=f.extend({},
n.cookie,b||{}),e=c.name||n.name||"Layout",d="",m="",g=false;c.expires.toUTCString?m=c.expires:typeof c.expires=="number"&&(m=new Date,c.expires>0?m.setDate(m.getDate()+c.expires):(m.setYear(1970),g=true));m&&(d+=";expires="+m.toUTCString());c.path&&(d+=";path="+c.path);c.domain&&(d+=";domain="+c.domain);c.secure&&(d+=";secure");g?(k.cookie={},document.cookie=e+"="+d):(k.cookie=ta(a||c.keys),document.cookie=e+"="+encodeURIComponent(Ha(k.cookie))+d);return f.extend({},k.cookie)}function Ia(a){if(a=
Fa(a))k.cookie=f.extend({},a),Ja(a);return a}function Ja(a){f.extend(true,n,a)}function ta(a){var b={},c={isClosed:"initClosed",isHidden:"initHidden"},e,d,m;if(!a)a=n.cookie.keys;f.isArray(a)&&(a=a.join(","));for(var a=a.replace(/__/g,".").split(","),g=0,i=a.length;g<i;g++)e=a[g].split("."),d=e[0],e=e[1],j.allPanes.indexOf(d)<0||(m=k[d][e],m!=void 0&&(e=="isClosed"&&k[d].isSliding&&(m=true),(b[d]||(b[d]={}))[c[e]?c[e]:e]=m));return b}function Ha(a){function b(a){var e=[],d=0,f,g,i;for(f in a)g=a[f],
i=typeof g,i=="string"?g='"'+g+'"':i=="object"&&(g=b(g)),e[d++]='"'+f+'":'+g;return"{"+e.join(",")+"}"}return b(a)}function Ga(a){try{return window.eval("("+a+")")||{}}catch(b){return{}}}q=__("Pane");t=__("Open");z=__("Close");F=__("Resize");J=__("Slide Open");w=__("Pin");v=__("Un-Pin");p=__("selector");T=__("Not enough room to show this pane.");o="Error Adding Button \n\nInvalid ";var n={name:"",scrollToBookmarkOnLoad:true,resizeWithWindow:true,resizeWithWindowDelay:200,resizeWithWindowMaxDelay:0,
onresizeall_start:null,onresizeall_end:null,onload:null,onunload:null,autoBindCustomButtons:false,zIndex:null,defaults:{applyDemoStyles:false,closable:true,resizable:true,slidable:true,initClosed:false,initHidden:false,contentSelector:".ui-layout-content",contentIgnoreSelector:".ui-layout-ignore",findNestedContent:false,paneClass:"ui-layout-pane",resizerClass:"ui-layout-resizer",togglerClass:"ui-layout-toggler",buttonClass:"ui-layout-button",minSize:0,maxSize:0,spacing_open:6,spacing_closed:6,togglerLength_open:50,
togglerLength_closed:50,togglerAlign_open:"center",togglerAlign_closed:"center",togglerTip_open:z,togglerTip_closed:t,togglerContent_open:"",togglerContent_closed:"",resizerDblClickToggle:true,autoResize:true,autoReopen:true,resizerDragOpacity:1,maskIframesOnResize:true,resizeNestedLayout:true,resizeWhileDragging:false,resizeContentWhileDragging:false,noRoomToOpenTip:T,resizerTip:F,sliderTip:J,sliderCursor:"pointer",slideTrigger_open:"click",slideTrigger_close:"mouseleave",hideTogglerOnSlide:false,
preventQuickSlideClose:!(!f.browser.webkit&&!f.browser.safari),showOverflowOnHover:false,enableCursorHotkey:true,customHotkeyModifier:"SHIFT",fxName:"slide",fxSpeed:null,fxSettings:{},fxOpacityFix:true,triggerEventsOnLoad:false,triggerEventsWhileDragging:true,onshow_start:null,onshow_end:null,onhide_start:null,onhide_end:null,onopen_start:null,onopen_end:null,onclose_start:null,onclose_end:null,onresize_start:null,onresize_end:null,onsizecontent_start:null,onsizecontent_end:null,onswap_start:null,
onswap_end:null,ondrag_start:null,ondrag_end:null},north:{paneSelector:".ui-layout-north",size:"auto",resizerCursor:"n-resize",customHotkey:""},south:{paneSelector:".ui-layout-south",size:"auto",resizerCursor:"s-resize",customHotkey:""},east:{paneSelector:".ui-layout-east",size:200,resizerCursor:"e-resize",customHotkey:""},west:{paneSelector:".ui-layout-west",size:200,resizerCursor:"w-resize",customHotkey:""},center:{paneSelector:".ui-layout-center",minWidth:0,minHeight:0},useStateCookie:false,cookie:{name:"",
autoSave:true,autoLoad:true,domain:"",path:"",expires:"",secure:false,keys:"north.size,south.size,east.size,west.size,north.isClosed,south.isClosed,east.isClosed,west.isClosed,north.isHidden,south.isHidden,east.isHidden,west.isHidden"}},ua={slide:{all:{duration:"fast"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},drop:{all:{duration:"slow"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},scale:{all:{duration:"fast"}}},
k={id:"layout"+(new Date).getTime(),initialized:false,container:{},north:{},south:{},east:{},west:{},center:{},cookie:{}},j={allPanes:"north,south,west,east,center",borderPanes:"north,south,west,east",altSide:{north:"south",south:"north",east:"west",west:"east"},hidden:{visibility:"hidden"},visible:{visibility:"visible"},zIndex:{pane_normal:1,resizer_normal:2,iframe_mask:2,pane_sliding:100,pane_animate:1E3,resizer_drag:1E4},resizers:{cssReq:{position:"absolute",padding:0,margin:0,fontSize:"1px",textAlign:"left",
overflow:"hidden"},cssDemo:{background:"#DDD",border:"none"}},togglers:{cssReq:{position:"absolute",display:"block",padding:0,margin:0,overflow:"hidden",textAlign:"center",fontSize:"1px",cursor:"pointer",zIndex:1},cssDemo:{background:"#AAA"}},content:{cssReq:{},cssDemo:{overflow:"auto",padding:"10px"},cssDemoPane:{overflow:"hidden",padding:0}},panes:{cssReq:{position:"absolute",margin:0},cssDemo:{padding:"10px",background:"#FFF",border:"1px solid #BBB",overflow:"auto"}},north:{side:"Top",sizeType:"Height",
dir:"horz",cssReq:{top:0,bottom:"auto",left:0,right:0,width:"auto"},pins:[]},south:{side:"Bottom",sizeType:"Height",dir:"horz",cssReq:{top:"auto",bottom:0,left:0,right:0,width:"auto"},pins:[]},east:{side:"Right",sizeType:"Width",dir:"vert",cssReq:{left:"auto",right:0,top:"auto",bottom:"auto",height:"auto"},pins:[]},west:{side:"Left",sizeType:"Width",dir:"vert",cssReq:{left:0,right:"auto",top:"auto",bottom:"auto",height:"auto"},pins:[]},center:{dir:"center",cssReq:{left:"auto",right:"auto",top:"auto",
bottom:"auto",height:"auto",width:"auto"}}},D={data:{},set:function(a,b,c){D.clear(a);D.data[a]=setTimeout(b,c)},clear:function(a){var b=D.data;b[a]&&(clearTimeout(b[a]),delete b[a])}},G=function(a){try{return typeof a=="string"||typeof a=="object"&&a.constructor.toString().match(/string/i)!==null}catch(b){return false}},y=function(a,b){return Math.max(a,b)},Wa=function(a){var b,c={cookie:{},defaults:{fxSettings:{}},north:{fxSettings:{}},south:{fxSettings:{}},east:{fxSettings:{}},west:{fxSettings:{}},
center:{fxSettings:{}}},a=a||{};a.effects||a.cookie||a.defaults||a.north||a.south||a.west||a.east||a.center?c=f.extend(true,c,a):f.each(a,function(a,d){b=a.split("__");if(!b[1]||c[b[0]])c[b[1]?b[0]:"defaults"][b[1]?b[1]:b[0]]=d});return c},Ka=function(a,b,c){function e(m){var g=j[m];g.doCallback?(d.push(m),m=g.callback.split(",")[1],m!=b&&!f.inArray(m,d)>=0&&e(m)):(g.doCallback=true,g.callback=a+","+b+","+(c?1:0))}var d=[];f.each(j.borderPanes.split(","),function(a,b){if(j[b].isMoving)return e(b),
false})},La=function(a){a=j[a];j.isLayoutBusy=false;delete a.isMoving;if(a.doCallback&&a.callback){a.doCallback=false;var b=a.callback.split(","),c=b[2]>0?true:false;b[0]=="open"?O(b[1],c):b[0]=="close"&&K(b[1],c);if(!a.doCallback)a.callback=null}},x=function(a,b){if(b){var c;try{if(typeof b=="function")c=b;else if(G(b))if(b.match(/,/)){var e=b.split(",");c=eval(e[0]);if(typeof c=="function"&&e.length>1)return c(e[1])}else c=eval(b);else return;if(typeof c=="function")return a&&s[a]?c(a,s[a],f.extend({},
k[a]),n[a],n.name):c(Ma,f.extend({},k),n,n.name)}catch(d){}}},Na=function(a,b){if(!a)return{};a.jquery||(a=f(a));var c={display:a.css("display"),visibility:a.css("visibility")};return b||c.display=="none"?(a.css({display:"block",visibility:"hidden"}),c):{}},Oa=function(a){if(!k.browser.mozilla){var b=s[a];k[a].tagName=="IFRAME"?b.css(j.hidden).css(j.visible):b.find("IFRAME").css(j.hidden).css(j.visible)}},V=function(a,b){a.jquery||(a=f(a));var c=Na(a),e=parseInt(f.curCSS(a[0],b,true),10)||0;a.css(c);
return e},ca=function(a,b){a.jquery&&(a=a[0]);var c="border"+b.substr(0,1).toUpperCase()+b.substr(1);return f.curCSS(a,c+"Style",true)=="none"?0:parseInt(f.curCSS(a,c+"Width",true),10)||0},H=function(a,b){var c=G(a),e=c?s[a]:f(a);isNaN(b)&&(b=c?L(a):e.outerWidth());if(b<=0)return 0;if(!k.browser.boxModel)return b;c=b-ca(e,"Left")-ca(e,"Right")-V(e,"paddingLeft")-V(e,"paddingRight");return c>0?c:0},I=function(a,b){var c=G(a),e=c?s[a]:f(a);isNaN(b)&&(b=c?L(a):e.outerHeight());if(b<=0)return 0;if(!k.browser.boxModel)return b;
c=b-ca(e,"Top")-ca(e,"Bottom")-V(e,"paddingTop")-V(e,"paddingBottom");return c>0?c:0},ka=function(a){var b=j[a].dir,a={minWidth:1001-H(a,1E3),minHeight:1001-I(a,1E3)};if(b=="horz")a.minSize=a.minHeight;if(b=="vert")a.minSize=a.minWidth;return a},Xa=function(a,b,c){var e=a;G(a)?e=s[a]:a.jquery||(e=f(a));a=I(e,b);e.css({height:a,visibility:"visible"});a>0&&e.innerWidth()>0?c&&e.data("autoHidden")&&(e.show().data("autoHidden",false),k.browser.mozilla||e.css(j.hidden).css(j.visible)):c&&!e.data("autoHidden")&&
e.hide().data("autoHidden",true)},P=function(a,b,c){if(!c)c=j[a].dir;G(b)&&b.match(/%/)&&(b=parseInt(b,10)/100);if(b===0)return 0;else if(b>=1)return parseInt(b,10);else if(b>0){var a=n,e;c=="horz"?e=u.innerHeight-(s.north?a.north.spacing_open:0)-(s.south?a.south.spacing_open:0):c=="vert"&&(e=u.innerWidth-(s.west?a.west.spacing_open:0)-(s.east?a.east.spacing_open:0));return Math.floor(e*b)}else if(a=="center")return 0;else{e=s[a];var c=c=="horz"?"height":"width",a=Na(e),d=e.css(c);e.css(c,"auto");
b=c=="height"?e.outerHeight():e.outerWidth();e.css(c,d).css(a);return b}},L=function(a,b){var c=s[a],e=n[a],d=k[a],f=b?e.spacing_open:0,e=b?e.spacing_closed:0;return!c||d.isHidden?0:d.isClosed||d.isSliding&&b?e:j[a].dir=="horz"?c.outerHeight()+f:c.outerWidth()+f},M=function(a,b){var c=n[a],e=k[a],d=j[a],f=d.dir;d.side.toLowerCase();d.sizeType.toLowerCase();var d=b!=void 0?b:e.isSliding,g=c.spacing_open,i=j.altSide[a],l=k[i],h=s[i],r=!h||l.isVisible===false||l.isSliding?0:f=="horz"?h.outerHeight():
h.outerWidth(),i=(!h||l.isHidden?0:n[i][l.isClosed!==false?"spacing_closed":"spacing_open"])||0,l=f=="horz"?u.innerHeight:u.innerWidth,h=ka("center"),h=f=="horz"?y(n.center.minHeight,h.minHeight):y(n.center.minWidth,h.minWidth),d=l-g-(d?0:P("center",h,f)+r+i),f=e.minSize=y(P(a,c.minSize),ka(a).minSize),g=c.maxSize?P(a,c.maxSize):1E5,d=Math.min(g,d),d=e.maxSize=d,e=e.resizerPosition={},g=u.insetTop,r=u.insetLeft,i=u.innerWidth,l=u.innerHeight,c=c.spacing_open;switch(a){case "north":e.min=g+f;e.max=
g+d;break;case "west":e.min=r+f;e.max=r+d;break;case "south":e.min=g+l-d-c;e.max=g+l-f-c;break;case "east":e.min=r+i-d-c,e.max=r+i-f-c}},W=function(a){var b={},c=b.css={},e={},d,m,g=a.offset();b.offsetLeft=g.left;b.offsetTop=g.top;f.each("Left,Right,Top,Bottom".split(","),function(f,g){d=c["border"+g]=ca(a,g);m=c["padding"+g]=V(a,"padding"+g);e[g]=d+m;b["inset"+g]=m});b.offsetWidth=a.innerWidth();b.offsetHeight=a.innerHeight();b.outerWidth=a.outerWidth();b.outerHeight=a.outerHeight();b.innerWidth=
b.outerWidth-e.Left-e.Right;b.innerHeight=b.outerHeight-e.Top-e.Bottom;c.width=a.width();c.height=a.height();return b},va=function(a,b){var c={},e=a[0].style,d=b.split(","),f="Top,Bottom,Left,Right".split(","),g="Color,Style,Width".split(","),i,l,h,j,k,n;for(j=0;j<d.length;j++)if(i=d[j],i.match(/(border|padding|margin)$/))for(k=0;k<4;k++)if(l=f[k],i=="border")for(n=0;n<3;n++)h=g[n],c[i+l+h]=e[i+l+h];else c[i+l]=e[i+l];else c[i]=e[i];return c},wa=function(a,b){var c=f(a),e=c.data("layoutRole"),d=c.data("layoutEdge"),
m=n[d][e+"Class"],d="-"+d,g=c.hasClass(m+"-closed")?"-closed":"-open",i=g=="-closed"?"-open":"-closed",g=m+"-hover "+(m+d+"-hover ")+(m+g+"-hover ")+(m+d+g+"-hover ");b&&(g+=m+i+"-hover "+(m+d+i+"-hover "));e=="resizer"&&c.hasClass(m+"-sliding")&&(g+=m+"-sliding-hover "+(m+d+"-sliding-hover "));return f.trim(g)},da=function(a,b){var c=b||this;f(c).addClass(wa(c))},N=function(a,b){var c=b||this;f(c).removeClass(wa(c,true))},Ya=function(a){f("body").disableSelection();da(a,this)},Pa=function(a,b){var c=
b||this,e=f(c).data("layoutEdge"),d=e+"ResizerLeave";D.clear(d);b?k[e].isResizing||f("body").enableSelection():(N(a,this),D.set(d,function(){Pa(a,c)},200))},Za=function(){var a=Number(n.resizeWithWindowDelay)||100;a>0&&(D.clear("winResize"),D.set("winResize",function(){D.clear("winResize");D.clear("winResizeRepeater");la()},a),D.data.winResizeRepeater||Qa())},Qa=function(){var a=Number(n.resizeWithWindowMaxDelay);a>0&&D.set("winResizeRepeater",function(){Qa();la()},a)},Ra=function(){var a=n;k.cookie=
ta();a.useStateCookie&&a.cookie.autoSave&&sa();x(null,a.onunload)},$a=function(){f.each(j.borderPanes.split(","),function(a,b){var c=n[b];if(c.enableCursorHotkey||c.customHotkey)return f(document).bind("keydown."+B,Y),false})},ab=function(){function a(a){for(var c in b)a[c]!=void 0&&(a[b[c]]=a[c],delete a[c])}h=Wa(h);var b={applyDefaultStyles:"applyDemoStyles"};a(h.defaults);f.each(j.allPanes.split(","),function(b,c){a(h[c])});h.effects&&(f.extend(ua,h.effects),delete h.effects);f.extend(n.cookie,
h.cookie);f.each("name,zIndex,scrollToBookmarkOnLoad,resizeWithWindow,resizeWithWindowDelay,resizeWithWindowMaxDelay,onresizeall,onresizeall_start,onresizeall_end,onload,onunload,autoBindCustomButtons,useStateCookie".split(","),function(a,b){h[b]!==void 0?n[b]=h[b]:h.defaults[b]!==void 0&&(n[b]=h.defaults[b],delete h.defaults[b])});f.each("paneSelector,resizerCursor,customHotkey".split(","),function(a,b){delete h.defaults[b]});f.extend(true,n.defaults,h.defaults);j.center=f.extend(true,{},j.panes,
j.center);var c=n.zIndex;if(c===0||c>0)j.zIndex.pane_normal=c,j.zIndex.resizer_normal=c+1,j.zIndex.iframe_mask=c+1;f.extend(n.center,h.center);var e=f.extend(true,{},n.defaults,h.defaults,n.center),c="paneClass,contentSelector,applyDemoStyles,triggerEventsOnLoad,showOverflowOnHover,onresize,onresize_start,onresize_end,resizeNestedLayout,resizeContentWhileDragging,onsizecontent,onsizecontent_start,onsizecontent_end".split(",");f.each(c,function(a,b){n.center[b]=e[b]});var d,m=n.defaults;f.each(j.borderPanes.split(","),
function(a,b){j[b]=f.extend(true,{},j.panes,j[b]);d=n[b]=f.extend(true,{},n.defaults,n[b],h.defaults,h[b]);if(!d.paneClass)d.paneClass="ui-layout-pane";if(!d.resizerClass)d.resizerClass="ui-layout-resizer";if(!d.togglerClass)d.togglerClass="ui-layout-toggler";f.each(["_open","_close",""],function(a,c){var e="fxName"+c,g="fxSpeed"+c,j="fxSettings"+c;d[e]=h[b][e]||h[b].fxName||h.defaults[e]||h.defaults.fxName||d[e]||d.fxName||m[e]||m.fxName||"none";var k=d[e];if(k=="none"||!f.effects||!f.effects[k]||
!ua[k]&&!d[j]&&!d.fxSettings)k=d[e]="none";k=ua[k]||{};e=k.all||{};k=k[b]||{};d[j]=f.extend({},e,k,m.fxSettings||{},m[j]||{},d.fxSettings,d[j],h.defaults.fxSettings,h.defaults[j]||{},h[b].fxSettings,h[b][j]||{});d[g]=h[b][g]||h[b].fxSpeed||h.defaults[g]||h.defaults.fxSpeed||d[g]||d[j].duration||d.fxSpeed||d.fxSettings.duration||m.fxSpeed||m.fxSettings.duration||k.duration||e.duration||"normal"})})},Sa=function(a){a=n[a].paneSelector;if(a.substr(0,1)==="#")return C.find(a).eq(0);else{var b=C.children(a).eq(0);
return b.length?b:C.children("form:first").children(a).eq(0)}},bb=function(){f.each(j.allPanes.split(","),function(a,b){var c=n[b],e=k[b],d=j[b],m=d.dir,g=b=="center",i={},l,h,r;Q[b]=false;l=s[b]=Sa(b);if(!l.length)return s[b]=false,true;l.data("layoutCSS")||l.data("layoutCSS",va(l,"position,top,left,bottom,right,width,height,overflow,zIndex,display,backgroundColor,padding,margin,border"));l.data("layoutName",n.name).data("layoutRole","pane").data("layoutEdge",b).css(d.cssReq).css("zIndex",j.zIndex.pane_normal).css(c.applyDemoStyles?
d.cssDemo:{}).addClass(c.paneClass+" "+c.paneClass+"-"+b).bind("mouseenter."+B,da).bind("mouseleave."+B,N);Ta(b,false);if(!g)h=e.size=P(b,c.size),d=P(b,c.minSize)||1,r=P(b,c.maxSize)||1E5,h>0&&(h=y(Math.min(h,r),d));e.tagName=f.prop?l.prop("tagName"):l.attr("tagName");e.edge=b;e.noRoom=false;e.isVisible=true;if(!g)e.isClosed=false,e.isSliding=false,e.isResizing=false,e.isHidden=false;switch(b){case "north":i.top=u.insetTop;i.left=u.insetLeft;i.right=u.insetRight;break;case "south":i.bottom=u.insetBottom;
i.left=u.insetLeft;i.right=u.insetRight;break;case "west":i.left=u.insetLeft;break;case "east":i.right=u.insetRight}if(m=="horz")i.height=y(1,I(b,h));else if(m=="vert")i.width=y(1,H(b,h));l.css(i);m!="horz"&&R(b,true);l.css({visibility:"visible",display:"block"});c.initClosed&&c.closable?K(b,true,true):(c.initHidden||c.initClosed)&&xa(b);c.showOverflowOnHover&&l.hover(U,ia)});Ua();f.each(j.borderPanes.split(","),function(a,b){s[b]&&k[b].isVisible&&(M(b),S(b))});R("center");f.each(j.allPanes.split(","),
function(a,b){var c=n[b];s[b]&&c.triggerEventsOnLoad&&k[b].isVisible&&x(b,c.onresize_end||c.onresize)});C.innerHeight()<2&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,u.ref))},Ua=function(a){if(!a||a=="all")a=j.borderPanes;f.each(a.split(","),function(a,c){var e=s[c];A[c]=false;E[c]=false;if(e){var e=n[c],d=k[c],m=e.resizerClass,g=e.togglerClass;j[c].side.toLowerCase();
var i="-"+c,l=A[c]=f("<div></div>"),h=e.closable?E[c]=f("<div></div>"):false;!d.isVisible&&e.slidable&&l.attr("title",e.sliderTip).css("cursor",e.sliderCursor);l.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+"-resizer":"").data("layoutRole","resizer").data("layoutEdge",c).css(j.resizers.cssReq).css("zIndex",j.zIndex.resizer_normal).css(e.applyDemoStyles?j.resizers.cssDemo:{}).addClass(m+" "+m+i).appendTo(C);h&&(h.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+
"-toggler":"").data("layoutRole","toggler").data("layoutEdge",c).css(j.togglers.cssReq).css(e.applyDemoStyles?j.togglers.cssDemo:{}).addClass(g+" "+g+i).appendTo(l).click(function(a){Z(c);a.stopPropagation()}).hover(da,N),e.togglerContent_open&&f("<span>"+e.togglerContent_open+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-open").css("display","none").appendTo(h).hover(da,N),e.togglerContent_closed&&f("<span>"+e.togglerContent_closed+"</span>").data("layoutRole",
"togglerContent").data("layoutEdge",c).addClass("content content-closed").css("display","none").appendTo(h).hover(da,N));cb(c);d.isVisible?ya(c):(za(c),ea(c,true))}});fa("all")},Ta=function(a,b){var c=n[a],e=c.contentSelector,d=s[a],f;e&&(f=Q[a]=c.findNestedContent?d.find(e).eq(0):d.children(e).eq(0));f&&f.length?(f.css(j.content.cssReq),c.applyDemoStyles&&(f.css(j.content.cssDemo),d.css(j.content.cssDemoPane)),k[a].content={},b!==false&&aa(a)):Q[a]=false},db=function(){var a;f.each("toggle,open,close,pin,toggle-slide,open-slide".split(","),
function(b,c){f.each(j.borderPanes.split(","),function(b,d){f(".ui-layout-button-"+c+"-"+d).each(function(){a=f(this).data("layoutName")||f(this).attr("layoutName");(a==void 0||a==n.name)&&Ca(this,c,d)})})})},cb=function(a){var b=typeof f.fn.draggable=="function",c;if(!a||a=="all")a=j.borderPanes;f.each(a.split(","),function(a,d){var m=n[d],g=k[d],i=j[d],l=i.dir=="horz"?"top":"left",h,r;if(!b||!s[d]||!m.resizable)return m.resizable=false,true;var o=A[d],p=m.resizerClass,q=p+"-drag",t=p+"-"+d+"-drag",
v=p+"-dragging",w=p+"-"+d+"-dragging",y=p+"-dragging-limit",z=false;g.isClosed||o.attr("title",m.resizerTip).css("cursor",m.resizerCursor);o.hover(Ya,Pa);o.draggable({containment:C[0],axis:i.dir=="horz"?"y":"x",delay:0,distance:1,helper:"clone",opacity:m.resizerDragOpacity,addClasses:false,zIndex:j.zIndex.resizer_drag,start:function(){m=n[d];g=k[d];r=m.resizeWhileDragging;if(false===x(d,m.ondrag_start))return false;j.isLayoutBusy=true;g.isResizing=true;D.clear(d+"_closeSlider");M(d);h=g.resizerPosition;
o.addClass(q+" "+t);z=false;c=f(m.maskIframesOnResize===true?"iframe":m.maskIframesOnResize).filter(":visible");var a,b=0;c.each(function(){a="ui-layout-mask-"+ ++b;f(this).data("layoutMaskID",a);f('<div id="'+a+'" class="ui-layout-mask ui-layout-mask-'+d+'"/>').css({background:"#fff",opacity:"0.001",zIndex:j.zIndex.iframe_mask,position:"absolute",width:this.offsetWidth+"px",height:this.offsetHeight+"px"}).css(f(this).position()).appendTo(this.parentNode)});f("body").disableSelection()},drag:function(a,
b){z||(b.helper.addClass(v+" "+w).children().css("visibility","hidden"),z=true,g.isSliding&&s[d].css("zIndex",j.zIndex.pane_sliding));var c=0;if(b.position[l]<h.min)b.position[l]=h.min,c=-1;else if(b.position[l]>h.max)b.position[l]=h.max,c=1;c?(b.helper.addClass(y),window.defaultStatus="Panel has reached its "+(c>0&&d.match(/north|west/)||c<0&&d.match(/south|east/)?"maximum":"minimum")+" size"):(b.helper.removeClass(y),window.defaultStatus="");r&&B(a,b,d)},stop:function(a,b){f("body").enableSelection();
window.defaultStatus="";o.removeClass(q+" "+t+" "+y);g.isResizing=false;j.isLayoutBusy=false;B(a,b,d,true)}});var B=function(a,b,d,e){var a=b.position,b=j[d],g;switch(d){case "north":g=a.top;break;case "west":g=a.left;break;case "south":g=u.offsetHeight-a.top-m.spacing_open;break;case "east":g=u.offsetWidth-a.left-m.spacing_open}if(e){if(f("div.ui-layout-mask").each(function(){this.parentNode.removeChild(this)}),false===x(d,m.ondrag_end||m.ondrag))return false}else c.each(function(){f("#"+f(this).data("layoutMaskID")).css(f(this).position()).css({width:this.offsetWidth+
"px",height:this.offsetHeight+"px"})});Aa(d,g-u["inset"+b.side])}})},xa=function(a,b){var c=n[a],e=k[a],d=s[a],f=A[a];if(d&&!e.isHidden&&!(k.initialized&&false===x(a,c.onhide_start)))if(e.isSliding=false,f&&f.hide(),!k.initialized||e.isClosed){if(e.isClosed=true,e.isHidden=true,e.isVisible=false,d.hide(),R(j[a].dir=="horz"?"all":"center"),k.initialized||c.triggerEventsOnLoad)x(a,c.onhide_end||c.onhide)}else e.isHiding=true,K(a,false,b)},ma=function(a,b,c,e){var d=k[a];if(s[a]&&d.isHidden&&false!==
x(a,n[a].onshow_start))d.isSliding=false,d.isShowing=true,b===false?K(a,true):O(a,false,c,e)},Z=function(a,b){G(a)||(a.stopImmediatePropagation(),a=f(this).data("layoutEdge"));var c=k[G(a)?f.trim(a):a==void 0||a==null?"":a];c.isHidden?ma(a):c.isClosed?O(a,!!b):K(a)},eb=function(a){var b=k[a];s[a].hide();b.isClosed=true;b.isVisible=false},K=function(a,b,c,e){function d(){if(i.isClosed){ea(a,true);var b=j.altSide[a];k[b].noRoom&&(M(b),S(b));if(!e&&(k.initialized||g.triggerEventsOnLoad))l||x(a,g.onclose_end||
g.onclose),l&&x(a,g.onshow_end||g.onshow),h&&x(a,g.onhide_end||g.onhide)}La(a)}if(k.initialized){var f=s[a],g=n[a],i=k[a],c=!c&&!i.isClosed&&g.fxName_close!="none",l=i.isShowing,h=i.isHiding;delete i.isShowing;delete i.isHiding;if(f&&g.closable&&(b||!i.isClosed||l))if(j.isLayoutBusy)Ka("close",a,b);else if(l||false!==x(a,g.onclose_start)){j[a].isMoving=true;j.isLayoutBusy=true;i.isClosed=true;i.isVisible=false;if(h)i.isHidden=true;else if(l)i.isHidden=false;i.isSliding?ga(a,false):R(j[a].dir=="horz"?
"all":"center",false);za(a);c?(na(a,true),f.hide(g.fxName_close,g.fxSettings_close,g.fxSpeed_close,function(){na(a,false);d()})):(f.hide(),d())}}else eb(a)},za=function(a){var b=A[a],c=E[a],e=n[a],d=j[a].side.toLowerCase(),m=e.resizerClass,g=e.togglerClass,i="-"+a;b.css(d,u["inset"+j[a].side]).removeClass(m+"-open "+m+i+"-open").removeClass(m+"-sliding "+m+i+"-sliding").addClass(m+"-closed "+m+i+"-closed").unbind("dblclick."+B);e.resizable&&typeof f.fn.draggable=="function"&&b.draggable("disable").removeClass("ui-state-disabled").css("cursor",
"default").attr("title","");c&&(c.removeClass(g+"-open "+g+i+"-open").addClass(g+"-closed "+g+i+"-closed").attr("title",e.togglerTip_closed),c.children(".content-open").hide(),c.children(".content-closed").css("display","block"));ra(a,false);k.initialized&&fa("all")},O=function(a,b,c,e){function d(){i.isVisible&&(Oa(a),i.isSliding||R(j[a].dir=="vert"?"center":"all",false),ya(a));La(a)}var f=s[a],g=n[a],i=k[a],c=!c&&i.isClosed&&g.fxName_open!="none",l=i.isShowing;delete i.isShowing;if(f&&(g.resizable||
g.closable)&&(!i.isVisible||i.isSliding))if(i.isHidden&&!l)ma(a,true);else if(j.isLayoutBusy)Ka("open",a,b);else if(false!==x(a,g.onopen_start))if(M(a,b),i.minSize>i.maxSize)ra(a,false),!e&&g.noRoomToOpenTip&&alert(g.noRoomToOpenTip);else{j[a].isMoving=true;j.isLayoutBusy=true;b?ga(a,true):i.isSliding?ga(a,false):g.slidable&&ea(a,false);i.noRoom=false;S(a);i.isVisible=true;i.isClosed=false;if(l)i.isHidden=false;c?(na(a,true),f.show(g.fxName_open,g.fxSettings_open,g.fxSpeed_open,function(){na(a,false);
d()})):(f.show(),d())}},ya=function(a,b){var c=s[a],e=A[a],d=E[a],m=n[a],g=k[a],i=j[a].side.toLowerCase(),l=m.resizerClass,h=m.togglerClass,r="-"+a;e.css(i,u["inset"+j[a].side]+L(a)).removeClass(l+"-closed "+l+r+"-closed").addClass(l+"-open "+l+r+"-open");g.isSliding?e.addClass(l+"-sliding "+l+r+"-sliding"):e.removeClass(l+"-sliding "+l+r+"-sliding");m.resizerDblClickToggle&&e.bind("dblclick",Z);N(0,e);m.resizable&&typeof f.fn.draggable=="function"?e.draggable("enable").css("cursor",m.resizerCursor).attr("title",
m.resizerTip):g.isSliding||e.css("cursor","default");d&&(d.removeClass(h+"-closed "+h+r+"-closed").addClass(h+"-open "+h+r+"-open").attr("title",m.togglerTip_open),N(0,d),d.children(".content-closed").hide(),d.children(".content-open").css("display","block"));ra(a,!g.isSliding);f.extend(g,W(c));k.initialized&&(fa("all"),aa(a,true));if(!b&&(k.initialized||m.triggerEventsOnLoad)&&c.is(":visible"))x(a,m.onopen_end||m.onopen),g.isShowing&&x(a,m.onshow_end||m.onshow),k.initialized&&(x(a,m.onresize_end||
m.onresize),ha(a))},Va=function(a){var b=typeof a,c=b=="string"?a:f(this).data("layoutEdge");b=="object"&&a.stopImmediatePropagation();k[c].isClosed?O(c,true):ga(c,true)},Ba=function(a){function b(){e.isClosed?ga(c,false):K(c)}var c=(G(a)?s[a]:f(this)).data("layoutEdge"),a=n[c],e=k[c];!e.isClosed&&!e.isResizing&&(a.slideTrigger_close=="click"?b():(!a.preventQuickSlideClose||!j.isLayoutBusy)&&D.set(c+"_closeSlider",b,300))},na=function(a,b){var c=s[a];if(b)c.css({zIndex:j.zIndex.pane_animate}),a==
"south"?c.css({top:u.insetTop+u.innerHeight-c.outerHeight()}):a=="east"&&c.css({left:u.insetLeft+u.innerWidth-c.outerWidth()});else{c.css({zIndex:k[a].isSliding?j.zIndex.pane_sliding:j.zIndex.pane_normal});a=="south"?c.css({top:"auto"}):a=="east"&&c.css({left:"auto"});var e=n[a];k.browser.msie&&e.fxOpacityFix&&e.fxName_open!="slide"&&c.css("filter")&&c.css("opacity")==1&&c[0].style.removeAttribute("filter")}},ea=function(a,b){var c=n[a],e=A[a],d=c.slideTrigger_open;if(e&&c.slidable){if(d.match(/mouseover/))d=
c.slideTrigger_open="mouseenter";else if(!d.match(/click|dblclick|mouseenter/))d=c.slideTrigger_open="click";e[b?"bind":"unbind"](d+"."+B,Va).css("cursor",b?c.sliderCursor:"default").attr("title",b?c.sliderTip:"")}},ga=function(a,b){function c(b){D.clear(a+"_closeSlider");b.stopPropagation()}var e=n[a],d=j.zIndex,f=e.slideTrigger_close,g=b?"bind":"unbind",i=s[a],l=A[a];k[a].isSliding=b;D.clear(a+"_closeSlider");b&&ea(a,false);i.css("zIndex",b?d.pane_sliding:d.pane_normal);l.css("zIndex",b?d.pane_sliding:
d.resizer_normal);if(!f.match(/click|mouseleave/))f=e.slideTrigger_close="mouseleave";l[g](f,Ba);f=="mouseleave"&&(i[g]("mouseleave."+B,Ba),l[g]("mouseenter."+B,c),i[g]("mouseenter."+B,c));b?f=="click"&&!e.resizable&&(l.css("cursor",b?e.sliderCursor:"default"),l.attr("title",b?e.togglerTip_open:"")):D.clear(a+"_closeSlider")},S=function(a,b,c,e){var b=n[a],d=k[a],f=j[a],g=s[a],i=A[a],l=f.dir=="vert",h=false;if(a=="center"||l&&d.noVerticalRoom)if((h=d.minHeight<=d.maxHeight&&(l||d.minWidth<=d.maxWidth))&&
d.noRoom){g.show();i&&i.show();d.isVisible=true;d.noRoom=false;if(l)d.noVerticalRoom=false;Oa(a)}else if(!h&&!d.noRoom)g.hide(),i&&i.hide(),d.isVisible=false,d.noRoom=true;if(a!="center")if(d.minSize<=d.maxSize){if(d.size>d.maxSize?ba(a,d.maxSize,c,e):d.size<d.minSize?ba(a,d.minSize,c,e):i&&g.is(":visible")&&(c=f.side.toLowerCase(),e=d.size+u["inset"+f.side],V(i,c)!=e&&i.css(c,e)),d.noRoom)d.wasOpen&&b.closable?b.autoReopen?O(a,false,true,true):d.noRoom=false:ma(a,d.wasOpen,true,true)}else if(!d.noRoom)d.noRoom=
true,d.wasOpen=!d.isClosed&&!d.isSliding,b.closable?K(a,true,true):xa(a,true)},Aa=function(a,b,c){var e=n[a],d=e.resizeWhileDragging&&!j.isLayoutBusy;e.autoResize=false;ba(a,b,c,d)},ba=function(a,b,c,e){var d=n[a],h=k[a],g=s[a],i=A[a],l=j[a].side.toLowerCase(),o="inset"+j[a].side,r=j.isLayoutBusy&&!d.triggerEventsWhileDragging,p;M(a);p=h.size;b=P(a,b);b=y(b,P(a,d.minSize));b=Math.min(b,h.maxSize);if(b<h.minSize)S(a,false,c);else if(e||b!=p)!c&&k.initialized&&h.isVisible&&x(a,d.onresize_start),g.css(j[a].sizeType.toLowerCase(),
y(1,j[a].dir=="horz"?I(a,b):H(a,b))),h.size=b,f.extend(h,W(g)),i&&g.is(":visible")&&i.css(l,b+u[o]),aa(a),!c&&!r&&k.initialized&&h.isVisible&&(x(a,d.onresize_end||d.onresize),ha(a)),c||(h.isSliding||R(j[a].dir=="horz"?"all":"center",r,e),fa("all")),a=j.altSide[a],b<p&&k[a].noRoom&&(M(a),S(a,false,c))},R=function(a,b,c){if(!a||a=="all")a="east,west,center";f.each(a.split(","),function(a,d){if(s[d]){var h=n[d],g=k[d],i=s[d],l=true,j={},l={top:L("north",true),bottom:L("south",true),left:L("west",true),
right:L("east",true),width:0,height:0};l.width=u.innerWidth-l.left-l.right;l.height=u.innerHeight-l.bottom-l.top;l.top+=u.insetTop;l.bottom+=u.insetBottom;l.left+=u.insetLeft;l.right+=u.insetRight;f.extend(g,W(i));if(d=="center"){if(!c&&g.isVisible&&l.width==g.outerWidth&&l.height==g.outerHeight)return true;f.extend(g,ka(d),{maxWidth:l.width,maxHeight:l.height});j=l;j.width=H(d,l.width);j.height=I(d,l.height);l=j.width>0&&j.height>0;if(!l&&!k.initialized&&h.minWidth>0){var r=h.minWidth-g.outerWidth,
o=n.east.minSize||0,p=n.west.minSize||0,q=k.east.size,t=k.west.size,v=q,w=t;r>0&&k.east.isVisible&&q>o&&(v=y(q-o,q-r),r-=q-v);r>0&&k.west.isVisible&&t>p&&(w=y(t-p,t-r),r-=t-w);if(r==0){q!=o&&ba("east",v,true);t!=p&&ba("west",w,true);R("center",b,c);return}}}else{f.extend(g,W(i),ka(d));if(!c&&!g.noVerticalRoom&&l.height==g.outerHeight)return true;j.top=l.top;j.bottom=l.bottom;j.height=I(d,l.height);g.maxHeight=y(0,j.height);l=g.maxHeight>0;if(!l)g.noVerticalRoom=true}l?(!b&&k.initialized&&x(d,h.onresize_start),
i.css(j),f.extend(g,W(i)),g.noRoom&&S(d),k.initialized&&aa(d)):!g.noRoom&&g.isVisible&&S(d);if(d=="center")i=k.browser,i=i.isIE6||i.msie&&!i.boxModel,s.north&&(i||k.north.tagName=="IFRAME")&&s.north.css("width",H(s.north,u.innerWidth)),s.south&&(i||k.south.tagName=="IFRAME")&&s.south.css("width",H(s.south,u.innerWidth));!b&&k.initialized&&g.isVisible&&(x(d,h.onresize_end||h.onresize),ha(d))}})},la=function(){f.extend(k.container,W(C));if(u.outerHeight){if(false===x(null,n.onresizeall_start))return false;
var a,b,c;f.each(["south","north","east","west"],function(a,d){s[d]&&(c=k[d],b=n[d],b.autoResize&&c.size!=b.size?ba(d,b.size,true,true):(M(d),S(d,false,true,true)))});R("all",true,true);fa("all");b=n;f.each(j.allPanes.split(","),function(c,d){if(a=s[d])k[d].isVisible&&x(d,b[d].onresize_end||b[d].onresize),ha(d)});x(null,b.onresizeall_end||b.onresizeall)}},ha=function(a){var b=s[a],c=Q[a];n[a].resizeNestedLayout&&(b.data("layoutContainer")?b.layout().resizeAll():c&&c.data("layoutContainer")&&c.layout().resizeAll())},
aa=function(a,b){if(!a||a=="all")a=j.allPanes;f.each(a.split(","),function(a,e){function d(a){return y(o.css.paddingBottom,parseInt(a.css("marginBottom"),10)||0)}function f(){var a=n[e].contentIgnoreSelector,a=i.nextAll().not(a||":lt(0)"),b=a.filter(":visible"),c=b.filter(":last");r={top:i[0].offsetTop,height:i.outerHeight(),numFooters:a.length,hiddenFooters:a.length-b.length,spaceBelow:0};r.spaceAbove=r.top;r.bottom=r.top+r.height;r.spaceBelow=c.length?c[0].offsetTop+c.outerHeight()-r.bottom+d(c):
d(i)}var g=s[e],i=Q[e],h=n[e],o=k[e],r=o.content;if(!g||!i||!g.is(":visible"))return true;if(false!==x(null,h.onsizecontent_start)){if(!j.isLayoutBusy||r.top==void 0||b||h.resizeContentWhileDragging)f(),r.hiddenFooters>0&&g.css("overflow")=="hidden"&&(g.css("overflow","visible"),f(),g.css("overflow","hidden"));g=o.innerHeight-(r.spaceAbove-o.css.paddingTop)-(r.spaceBelow-o.css.paddingBottom);if(!i.is(":visible")||r.height!=g)Xa(i,g,true),r.height=g;k.initialized&&(x(e,h.onsizecontent_end||h.onsizecontent),
ha(e))}})},fa=function(a){if(!a||a=="all")a=j.borderPanes;f.each(a.split(","),function(a,c){var e=n[c],d=k[c],h=s[c],g=A[c],i=E[c],l;if(h&&g){var o=j[c].dir,r=d.isClosed?"_closed":"_open",p=e["spacing"+r],q=e["togglerAlign"+r],r=e["togglerLength"+r],t;if(p==0)g.hide();else{!d.noRoom&&!d.isHidden&&g.show();o=="horz"?(t=h.outerWidth(),d.resizerLength=t,g.css({width:y(1,H(g,t)),height:y(0,I(g,p)),left:V(h,"left")})):(t=h.outerHeight(),d.resizerLength=t,g.css({height:y(1,I(g,t)),width:y(0,H(g,p)),top:u.insetTop+
L("north",true)}));N(e,g);if(i){if(r==0||d.isSliding&&e.hideTogglerOnSlide){i.hide();return}else i.show();if(!(r>0)||r=="100%"||r>t)r=t,q=0;else if(G(q))switch(q){case "top":case "left":q=0;break;case "bottom":case "right":q=t-r;break;default:q=Math.floor((t-r)/2)}else d=parseInt(q,10),q=q>=0?d:t-r+d;if(o=="horz"){var v=H(i,r);i.css({width:y(0,v),height:y(1,I(i,p)),left:q,top:0});i.children(".content").each(function(){l=f(this);l.css("marginLeft",Math.floor((v-l.outerWidth())/2))})}else{var w=I(i,
r);i.css({height:y(0,w),width:y(1,H(i,p)),top:q,left:0});i.children(".content").each(function(){l=f(this);l.css("marginTop",Math.floor((w-l.outerHeight())/2))})}N(0,i)}!k.initialized&&e.initHidden&&(g.hide(),i&&i.hide())}}})},C=f(this).eq(0);if(!C.length)return null;if(C.data("layoutContainer"))return f.extend({},window[C.data("layoutContainer")]);var s={},Q={},A={},E={},u=k.container,B=k.id;(function(){ab();var a=n;if(false===x(null,a.onload))return false;if(!Sa("center").length)return alert("UI Layout Initialization Error\n\nThe center-pane element does not exist.\n\nThe center-pane is a required element."),
null;a.useStateCookie&&a.cookie.autoLoad&&Ia();k.browser={mozilla:f.browser.mozilla,webkit:f.browser.webkit||f.browser.safari,msie:f.browser.msie,isIE6:f.browser.msie&&f.browser.version==6,boxModel:f.support.boxModel};var b=C,c=u.tagName=f.prop?b.prop("tagName"):b.attr("tagName"),e=c=="BODY",d={};u.selector=b.selector.split(".slice")[0];u.ref=c+"/"+u.selector;b.data("layoutContainer",B).data("layoutName",n.name);b.data("layoutCSS")||(e?(d=f.extend(va(b,"position,margin,padding,border"),{height:b.css("height"),
overflow:b.css("overflow"),overflowX:b.css("overflowX"),overflowY:b.css("overflowY")}),c=f("html"),c.data("layoutCSS",{height:"auto",overflow:c.css("overflow"),overflowX:c.css("overflowX"),overflowY:c.css("overflowY")})):d=va(b,"position,margin,padding,border,top,bottom,left,right,width,height,overflow,overflowX,overflowY"),b.data("layoutCSS",d));try{if(e)f("html").css({height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden"}),f("body").css({position:"relative",height:"100%",overflow:"hidden",
overflowX:"hidden",overflowY:"hidden",margin:0,padding:0,border:"none"});else{var d={overflow:"hidden"},h=b.css("position");b.css("height");if(!b.data("layoutRole")&&(!h||!h.match(/fixed|absolute|relative/)))d.position="relative";b.css(d);b.is(":visible")&&b.innerHeight()<2&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,u.ref))}}catch(g){}f.extend(k.container,W(b));bb();aa();
if(a.scrollToBookmarkOnLoad)b=self.location,b.hash&&b.replace(b.hash);a.autoBindCustomButtons&&db();$a();a.resizeWithWindow&&!C.data("layoutRole")&&f(window).bind("resize."+B,Za);f(window).bind("unload."+B,Ra);k.initialized=true})();var Ma={options:n,state:k,container:C,panes:s,contents:Q,resizers:A,togglers:E,toggle:Z,hide:xa,show:ma,open:O,close:K,slideOpen:Va,slideClose:Ba,slideToggle:function(a){Z(a,true)},initContent:Ta,sizeContent:aa,sizePane:Aa,swapPanes:function(a,b){function c(a){var b=s[a],
c=Q[a];return!b?false:{pane:a,P:b?b[0]:false,C:c?c[0]:false,state:f.extend({},k[a]),options:f.extend({},n[a])}}function e(a,b){if(a){var c=a.P,d=a.C,e=a.pane,h=j[b],m=h.side.toLowerCase(),o="inset"+h.side,p=f.extend({},k[b]),q=n[b],t={resizerCursor:q.resizerCursor};f.each("fxName,fxSpeed,fxSettings".split(","),function(a,b){t[b]=q[b];t[b+"_open"]=q[b+"_open"];t[b+"_close"]=q[b+"_close"]});s[b]=f(c).data("layoutEdge",b).css(j.hidden).css(h.cssReq);Q[b]=d?f(d):false;n[b]=f.extend({},a.options,t);k[b]=
f.extend({},a.state);c.className=c.className.replace(RegExp(q.paneClass+"-"+e,"g"),q.paneClass+"-"+b);Ua(b);h.dir!=j[e].dir?(c=g[b]||0,M(b),c=y(c,k[b].minSize),Aa(b,c,true)):A[b].css(m,u[o]+(k[b].isVisible?L(b):0));a.state.isVisible&&!p.isVisible?ya(b,true):(za(b),ea(b,true));a=null}}k[a].edge=b;k[b].edge=a;var d=false;false===x(a,n[a].onswap_start)&&(d=true);!d&&false===x(b,n[b].onswap_start)&&(d=true);if(d)k[a].edge=a,k[b].edge=b;else{var d=c(a),h=c(b),g={};g[a]=d?d.state.size:0;g[b]=h?h.state.size:
0;s[a]=false;s[b]=false;k[a]={};k[b]={};E[a]&&E[a].remove();E[b]&&E[b].remove();A[a]&&A[a].remove();A[b]&&A[b].remove();A[a]=A[b]=E[a]=E[b]=false;e(d,b);e(h,a);d=h=g=null;s[a]&&s[a].css(j.visible);s[b]&&s[b].css(j.visible);la();x(a,n[a].onswap_end||n[a].onswap);x(b,n[b].onswap_end||n[b].onswap)}},resizeAll:la,destroy:function(){f(window).unbind("."+B);f(document).unbind("."+B);window[B]=null;var a=u.tagName=="BODY",b,c,e,d;f.each(j.allPanes.split(","),function(a,g){b=s[g];if(!b)return true;g!="center"&&
(E[g]&&E[g].remove(),A[g].remove());c=n[g].paneClass;e=c+"-"+g;d=[c,c+"-open",c+"-closed",c+"-sliding",e,e+"-open",e+"-closed",e+"-sliding"];f.merge(d,wa(b,true));b.removeClass(d.join(" ")).removeData("layoutRole").removeData("layoutEdge").unbind("."+B).unbind("mouseenter").unbind("mouseleave");b.data("layoutContainer")||b.css(b.data("layoutCSS"))});C.removeData("layoutContainer");C.data("layoutEdge")||C.css(C.data("layoutCSS"));a&&f("html").css(f("html").data("layoutCSS"));Ra();(a=n.name)&&window[a]&&
(window[a]=null)},setSizeLimits:M,bindButton:Ca,addToggleBtn:oa,addOpenBtn:pa,addCloseBtn:Da,addPinBtn:Ea,allowOverflow:U,resetOverflow:ia,encodeJSON:Ha,decodeJSON:Ga,getState:ta,getCookie:Fa,saveCookie:sa,deleteCookie:function(){sa("",{expires:-1})},loadCookie:Ia,loadState:Ja,cssWidth:H,cssHeight:I};return window[B]=Ma}})(jQuery);
var layoutState={options:{layoutName:"mywebsql",keys:"north__size,south__size,east__size,west__size,north__isClosed,south__isClosed,east__isClosed,west__isClosed,north__isHidden,south__isHidden,east__isHidden,west__isHidden",domain:"",path:"",expires:"60",secure:false},data:{},clear:function(f){this.save(f,"layout",{expires:-1})},save:function(f,t,h){var h=jQuery.extend({},this.options,h||{}),o=window[f||h.layoutName];if(!t)t=h.keys;typeof t=="string"&&(t=t.split(","));if(!o||!o.state||!t.length)return false;
var p=typeof h.expires=="number",q=new Date,X="",z=false;if(p||h.expires.toUTCString)p?h.expires<=0?(q.setYear(1970),z=true):q.setTime(q.getTime()+h.expires*864E5):q=h.expires,X+=";expires="+q.toUTCString();h.path&&(X+=";path="+h.path);h.domain&&(X+=";domain="+h.domain);h.secure&&(X+=";secure");if(z)this.data={},$.cookies.set(f||h.layoutName,X,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME});else{for(var o=o.state,p={},q={isClosed:"initClosed",isHidden:"initHidden"},z=t[0].indexOf("__")>0?"__":".",
v,w,F,J=0;J<t.length;J++)v=t[J].split(z),w=v[0],v=v[1],"north,south,east,west,center".indexOf(w)<0||(F=v=="isClosed"?o[w][v]||o[w].isSliding:o[w][v],F!=void 0&&(z=="."?(p[w]||(p[w]={}),p[w][q[v]?q[v]:v]=F):p[w+z+(q[v]?q[v]:v)]=F));this.data=p;$.cookies.set(f||h.layoutName,encodeURIComponent(JSON.stringify(this.data))+X,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME})}return this.data},load:function(f){if(!f)f=this.options.layoutName;if(!f)return{};var t={};(ck=$.cookies.get(f))&&(t=JSON.parse(decodeURIComponent(ck)));
return this.data=t}};
