function logout(){optionsConfirm(__("Are you sure you want to logout?"),"sess.logout",function(a,b,c){a&&(c&&optionsConfirmSave(b),wrkfrmSubmit("logout","","",""))})}
function dbSelect(){arguments.length==1?(loc="?reload=1&db="+escape(arguments[0]),window.location=loc):(db=document.getElementById("dblist").options[document.getElementById("dblist").selectedIndex].text,data="db="+escape(db),$.ajax({type:"GET",url:"?",data:data,success:function(a){success=$(a).html();success=="1"?(objectsRefresh(),infoDefault()):jAlert(__("Operation failed"))},dataType:"html"}))}
function dbDrop(a){msg=str_replace("{{NAME}}","<b>"+a+"</b>",__("Are you sure you want to DROP the database {{NAME}}?"));optionsConfirm(msg,"db.drop",function(b,c,d){b&&(d&&optionsConfirmSave(c),wrkfrmSubmit("dbdrop",type,a))})}function dbEmpty(a){msg=str_replace("{{NAME}}","<b>"+a+"</b>",__("Are you sure you want to DROP all objects from the database {{NAME}}?"));optionsConfirm(msg,"db.empty",function(b,c,d){b&&(d&&optionsConfirmSave(c),wrkfrmSubmit("dbempty",type,a))})}
function dbCreate(a){if(arguments.length&&a){if(name=$.trim($("#dbname").val()),name!="")return wrkfrmSubmit("dbcreate","",name,$("#dbselect").attr("checked")?"1":"0"),$("#dialog-dbcreate").dialog("close"),false}else $("#dbname").val(""),$("#dbselect").attr("checked",false),uiCreateDialog("dbcreate"),$("#dialog-dbcreate").dialog("open")}
function objectsRefresh(){state=[];$("#tablelist .expandable").each(function(){state.push($(this).attr("id"))});wrkfrmSubmit("objlist","","","",function(a){objListHandler(a,state)})}function objDefault(a,b){$(currentTreeItem).removeClass("current");currentTreeItem=$("#"+b);currentTreeItem.addClass("current").find("a").blur();name=currentTreeItem.find("a").text();wrkfrmSubmit("showinfo",a,name,"")}function objCreate(a){taskbar.openDialog("objcreate_"+a,"?q=wrkfrm&type=objcreate&id="+a,600,490)}
function objTruncate(a,b){msg=str_replace("{{NAME}}",b,__("Are you sure you want to truncate the table {{NAME}}?"));optionsConfirm(msg,"obj.truncate",function(c,d,e){c&&(e&&optionsConfirmSave(d),wrkfrmSubmit("truncate",a,b))})}function objDrop(a,b){msg=str_replace("{{NAME}}","<br>"+b,__("Are you sure you want to drop this object? {{NAME}}"));optionsConfirm(msg,"obj.drop",function(c,d,e){c&&(e&&optionsConfirmSave(d),wrkfrmSubmit("drop",a,b))})}
function objRename(a,b){jPrompt(__("Enter new name for the database object"),b,__("Rename Object"),function(c){c!=null&&(c&&c!=b?wrkfrmSubmit("rename",a,b,c):jAlert(__("Enter new name for the database object")))})}function objCopy(a,b){jPrompt(__("Enter new name for the database object"),b+"_copy",__("Copy Object"),function(c){c!=null&&(c&&c!=b?wrkfrmSubmit("copy",a,b,c):jAlert(__("Enter new name for the database object")))})}
function tableCreate(){taskbar.openDialog("editable","?q=wrkfrm&type=createtbl",780,440,true)}function tableSelect(a){st=sql_delimiter+"select * from "+BACKQUOTE+a+BACKQUOTE;setSqlCode(st,1)}function tableInsert(a){wrkfrmSubmit("tableinsert","",a)}function tableUpdate(a){wrkfrmSubmit("tableupdate","",a)}function tableDescribe(a){wrkfrmSubmit("query","","","describe "+BACKQUOTE+a+BACKQUOTE)}
function tableViewData(a){q="select * from "+BACKQUOTE+a+BACKQUOTE;setSqlCode(sql_delimiter+q,1);wrkfrmSubmit("query","table","",a)}function tableAlter(a){taskbar.openDialog("editable-"+a,"?q=wrkfrm&type=altertbl&name="+escape(a),780,440,true)}function tableIndexes(a){taskbar.openDialog("indexes-"+a,"?q=wrkfrm&type=indexes&name="+escape(a),680,430,true)}function tableEngine(a){taskbar.openModal("table-engine","?q=wrkfrm&type=enginetype&name="+escape(a),280,190,true)}
function showCreateCmd(a,b){wrkfrmSubmit("showcreate",a,b,"")}function dataImport(){taskbar.openDialog("data-import","?q=wrkfrm&type=import",610,360)}function resultsExport(){numRecords==0?jAlert(__("There is no record in the results to export"),__("Exports results")):taskbar.openModal("data-export","?q=wrkfrm&type=exportres",400,290)}function dataExport(){taskbar.openDialog("data-export","?q=wrkfrm&type=export",600,420)}
function tableExport(a){taskbar.openDialog("data-export","?q=wrkfrm&type=exporttbl&table="+a,400,280)}function exportData(){id=arguments.length>0?arguments[0]:"";name=arguments.length>1?arguments[1]:"";query=arguments.length>2?arguments[2]:"";wrkfrmSubmit("dl","export"+id,name,query)}function repairTables(){wrkfrmSubmit("dbrepair","","","")}function helpShowAll(){taskbar.openDialog("help","?q=wrkfrm&type=help",680,440)}
function helpQuickTutorial(){$('<link id="ehelp_css">').appendTo("head").attr({rel:"stylesheet",type:"text/css",href:"img/ehelp.css"});$.getScript("cache.php?script=ehelp",function(){taskbar.minimizeAll();showEHelp()})}function helpOnlineDocs(){window.open("http://mywebsql.net/docs")}function helpReportBug(){window.open("http://mywebsql.net/support/bugreport/")}function helpRequestFeature(){window.open("http://mywebsql.net/support/requests/")}
function helpCheckUpdates(){url="http://mywebsql.net/updates.php?c=MyWebSQL&l="+escape(APP_LANGUAGE)+"&v="+escape(APP_VERSION)+"&t="+escape(THEME_PATH);taskbar.openModal("update-check",url,180,160);$("#dialog-update-check").siblings(".ui-dialog-titlebar").find(".ui-dialog-title").html(__("Check for Updates"))}function interfaceTheme(a){data="theme="+escape(a);$.ajax({type:"GET",url:"?",data:data,success:function(){window.location=window.location},dataType:"html"})}
function interfaceLang(a){data="lang="+escape(a);$.ajax({type:"GET",url:"?",data:data,success:function(){window.location=window.location},dataType:"html"})}function toolsOptions(){taskbar.openModal("tools-options","?q=wrkfrm&type=options",500,260)}function toolsProcManager(){taskbar.openDialog("tools-proc","?q=wrkfrm&type=processes",560,380)}function toolsDbCheck(){taskbar.openDialog("tools-check","?q=wrkfrm&type=dbrepair",600,420)}
function toolsDbSearch(){taskbar.openDialog("tools-search","?q=wrkfrm&type=search",620,450)}function toolsUsers(){taskbar.openDialog("tools-users","?q=wrkfrm&type=usermanager",620,440)}function infoDefault(){$("#screen-wait").remove();wrkfrmSubmit("info","","","")}function infoServer(){wrkfrmSubmit("infoserver","","","")}function infoVariables(){wrkfrmSubmit("infovars","","","")}function infoDatabase(){wrkfrmSubmit("infodb","","","")}function copyColumn(){}function copyText(){}
function sqlFilterText(){};
