var curEditField=null,curEditType=null,fieldInfo=null,editToolbarTimer=null,editOptions={sortable:true,highlight:true,selectable:true,editEvent:"dblclick",editFunc:editTableCell},selectedRow=-1,res_modified=false;
function setupTable(a,b){res_modified=false;b.editEvent||(b.editEvent="dblclick");b.editFunc||(b.editFunc=editTableCell);if(b.sortable)sorttable.DATE_RE=/^(\d\d?)[\/\.-](\d\d?)[\/\.-]((\d\d)?\d\d)$/,table=document.getElementById(a),sorttable.makeSortable(table);b.highlight&&($("#"+a+" tr").live("mouseover",function(){$(this).addClass("hl")}),$("#"+a+" tr").live("mouseout",function(){$(this).removeClass("hl")}));b.selectable&&$("#"+a+" tr").live("click",function(){selectedRow!=null&&$(selectedRow).removeClass("sel");
$(this).addClass("sel");selectedRow=this});b.editable&&(editOptions=b,$("#"+a+" td.edit").bind(b.editEvent,b.editFunc),$("#inplace-text textarea").unbind("keydown").bind("keydown",checkEditField).blur(function(){closeEditor(true)}))}
function editTableCell(){editToolbarTimer&&(window.clearTimeout(editToolbarTimer),editToolbarTimer=null);td=$(this);curEditField!=null&&closeEditor(true);isBlob=td.find("span.i").length;txt=(isText=td.find("span.d").length)?td.find("span.d").text():isBlob?td.find("span.i").text():td.text();tstyle=td.hasClass("tr")?"right":"left";td.data("defText",txt);curEditField=this;index=td.index()-2;fi=getFieldInfo(index);w=td.width()-(isBlob?22:0);h=td.height();td.attr("width",w);input=createCellEditor(td,fi,
txt,w,h,tstyle);setTimeout(function(){input.focus()},50);document.getElementById("editToolbar")&&$("#editToolbar").show().position({of:td,my:"left bottom",at:"left top",offset:0})}
function closeEditor(a,b){if(curEditField){obj=$(curEditField);txt="";var c={};if(a){if(arguments.length>1&&b==null?(c.value="NULL",c.setNull=true):(txt=c.value=curEditType=="simple"?obj.find("input").val():$("#inplace-text textarea").val(),c.setNull=false),c.value!=obj.data("defText")||c.setNull&&!obj.hasClass("tnl")||!c.setNull&&obj.hasClass("tnl"))obj.parent().hasClass("n")||obj.parent().addClass("x"),obj.data("edit",c).addClass("x"),res_modified=true,typeof showNavBtn=="function"&&showNavBtn("update",
"gensql"),c.setNull?obj.removeClass("tl").addClass("tnl"):obj.removeClass("tnl").addClass("tl"),txt=c.value}else txt=obj.data("defText");curEditType=="text"?(c.setNull?obj.find("span.i").text("NULL").removeClass("tl").addClass("tnl"):obj.find("span.i").text(txt.length==0?"":txt.length<=MAX_TEXT_LENGTH_DISPLAY?txt:"Text Data ["+formatBytes(txt.length)+"]").removeClass("tnl"),obj.find("span.d").text(txt)):obj.find("span.i").length==0?obj.text(txt):obj.find("span.i").text(txt);obj.removeAttr("width");
curEditField=null;curEditType=="text"&&$("#inplace-text").hide();document.getElementById("editToolbar")&&(editToolbarTimer=window.setTimeout(function(){document.getElementById("editToolbar").style.display="none";editToolbarTimer=null},100))}}
function checkEditField(a){keys=curEditType=="text"?[9]:[13,9,38,40];if(keys.indexOf(a.keyCode)!=-1){a.preventDefault();elem=false;if(a.keyCode==9)elem=a.shiftKey?$(curEditField).prev(".edit"):$(curEditField).next(".edit"),elem.length||(tr=a.shiftKey?$(curEditField).parent().prev():$(curEditField).parent().next(),tr.length&&(elem=a.shiftKey?tr.find("td.edit:last"):tr.find("td.edit:first")));else if(a.keyCode==38||a.keyCode==40)tr=a.keyCode==38?$(curEditField).parent().prev():$(curEditField).parent().next(),
tr.length&&(elem=tr.find("td").eq($(curEditField).index()));closeEditor(true);elem&&elem.length&&elem.trigger(editOptions.editEvent)}else a.keyCode==27&&closeEditor(false)}
function createCellEditor(a,b,c,d,f,e){curEditType="simple";keyEvent="keydown";input=null;code='<form name="cell_editor_form" class="cell_editor_form" action="javascript:void(0);">';if(b.blob==1)b.type=="binary"?(code+='<input type="text" readonly="readonly" name="cell_editor" class="cell_editor" style="text-align:'+e+";width: "+d+'px;" />',code+="</form>",a.find("span.i").html(code),input=a.find("input"),input.val(c).bind(keyEvent,checkEditField).blur(function(){closeEditor(true)})):(span=$(a).find("span.d"),
c=span.text(),d=a.width()-20,d<200&&(d=200),textarea=$("#inplace-text textarea"),textarea.width(d).val(c),$("#inplace-text").show().position({of:a,my:"left top",at:"left top",offset:0}),curEditType="text",input=textarea);else switch(b.type){default:code+='<input type="text" name="cell_editor" class="cell_editor" style="text-align:'+e+";width: "+d+'px;" />',code+="</form>",a.html(code),input=a.find("input"),input.val(c).select().bind(keyEvent,checkEditField).blur(function(){closeEditor(true)})}return input}
;
